#!/bin/sh

DATABASE="-d/home/christof/berlios/berlios.db"

checkout() {
  mt $DATABASE -bmanuproc.berlios.de/ManuProC_Base co ManuProC_Base
  mt $DATABASE -bmanuproc.berlios.de/GtkmmAddons co GtkmmAddons
  mt $DATABASE -bmanuproc.berlios.de/ManuProC_Widgets co ManuProC_Widgets
  mt $DATABASE -bmidgard.berlios.de/midgard co midgard
  mt $DATABASE -bmidgard.berlios.de/debian co debian
}

configure() {
  echo ========  ManuProC_Base ========
  ( cd ManuProC_Base && (./autogen.sh $* ; make ) )
  echo ========== GtkmmAddons ========
  ( cd GtkmmAddons && (./autogen.sh $* ; make ) )
  echo ========  ManuProC_Widgets ========
  ( cd ManuProC_Widgets && ( ./autogen.sh $* ; make ) )
  echo ============ Magus ========
  ( cd midgard && ./autogen.sh $* )
}

if [ "_$1" = "_checkout" -o "_$1" = "_co" ] 
then
  checkout
elif [ "_$1" = "_configure" ]
then
  configure $2 $3 $4 $5 $6 $7 $8 $9
else
  echo "Magus monotone Installierer, Gtk2, $Revision: 1.1 $"
  echo
  echo "USAGE: $0 <Befehl>"
  echo "Befehle: checkout co configure"
  echo
  echo "Vorsicht die Pakete werden in $PWD ausgepackt"
fi
