Summary: MAGUS - Midgard Abenteurer Generieren Und Steigern
Name: magus-data
Version: 0.8.14
Release: 1
Copyright: misc
Group: application/games
Distribution: SuSE 8.1
Url: http://midgard.berlios.de
Excludeos: noarch

%description
MAGUS ist ein Abenteurer Generierungs- und Steigerungstool für das Fantasyrollenspiel Midgard
Dieses RPM Paket beinhaltet die für die Benutzung von MAGUS notwendigen
Daten und Hilfeseiten. 



%clean



%files
/usr/share/magus/docs/VorausAllg.html
/usr/share/magus/docs/BMod_St_Zaub.html
/usr/share/magus/docs/Bedienung_Ausruest.html
/usr/share/magus/docs/BGen_Hand.html
/usr/share/magus/docs/Postgres.html
/usr/share/magus/docs/InstallAllg.html
/usr/share/magus/docs/image/WinLogo-small.png
/usr/share/magus/docs/image/MAGUS-Logo-small.png
/usr/share/magus/docs/image/icons/Icon-NSC.png
/usr/share/magus/docs/image/icons/Icon-Hausregeln.png
/usr/share/magus/docs/image/icons/Win-Icon-NSC.png
/usr/share/magus/docs/image/icons/Icon-3-T-Maus.png
/usr/share/magus/docs/image/icons/MidgardLogo-small.png
/usr/share/magus/docs/image/icons/Win-Icon-Wizard.png
/usr/share/magus/docs/image/icons/Icon-Wizard.png
/usr/share/magus/docs/image/NavBar/Fert_Lesen.png
/usr/share/magus/docs/image/NavBar/0-MagLogo.png
/usr/share/magus/docs/image/NavBar/Zauberstab4.png
/usr/share/magus/docs/image/NavBar/midgard_logo.png
/usr/share/magus/docs/image/NavBar/0-MidLogo.png
/usr/share/magus/docs/image/NavBar/Disk-Down.png
/usr/share/magus/docs/image/NavBar/Abwehr.png
/usr/share/magus/docs/image/NavBar/Info-trans.png
/usr/share/magus/docs/image/Install/MAGUS-Logo-Win-med.png
/usr/share/magus/docs/image/Install/MAGUS-Logo-orig-med.png
/usr/share/magus/docs/image/Install/MAGUS-Tux-Logo-med.png
/usr/share/magus/docs/image/magus-fav.ico
/usr/share/magus/docs/image/MAGUS-Logo-Text-halb.png
/usr/share/magus/docs/image/Bedienung/Select/GW-Sel-Dice.png
/usr/share/magus/docs/image/Bedienung/Select/GW-Sel-Herk.png
/usr/share/magus/docs/image/Bedienung/Select/ZG-GradGFP.png
/usr/share/magus/docs/image/Bedienung/Select/GW-Sel-Typ.png
/usr/share/magus/docs/image/Bedienung/Select/ZG-Prototyp.png
/usr/share/magus/docs/image/Bedienung/Select/GW-Sel-Sex.png
/usr/share/magus/docs/image/Bedienung/Select/GW-Sel-Species.png
/usr/share/magus/docs/image/Bedienung/Select/LS-Sel-Opt.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Praxis.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-SpraUSchri-PP.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Help.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-LPunkte.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Anleit.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Neu.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Menu.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Open.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Forward.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-mit-EP.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS_Button-Geld.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Back.png
/usr/share/magus/docs/image/Bedienung/Buttons/Welc_Button_Hack.png
/usr/share/magus/docs/image/Bedienung/Buttons/GW_Button_AbgelWerte.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-SpezWaf.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-LPEdit.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-PPin.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Alles-Anpass.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Zeit.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Win-Button-Waffen.png
/usr/share/magus/docs/image/Bedienung/Buttons/GW_Win_Button_AbgelWerte.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-AngebFert.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Info.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-GFP-in.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-Herkunft.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Save.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Print.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-Ausruest.png
/usr/share/magus/docs/image/Bedienung/Buttons/Welc_Button_Active.png
/usr/share/magus/docs/image/Bedienung/Buttons/Welc_Button_Rand.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Unterweisung.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Bes-Rue.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Exit.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Zaub-Roll.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Verlernen.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Bes-MagBon.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Help.png
/usr/share/magus/docs/image/Bedienung/Buttons/GW_Win_Button_Eigenschaften.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Red.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Menu.png
/usr/share/magus/docs/image/Bedienung/Buttons/Welc_Button_New.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Abwehr.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Win-Button-LPEdit.png
/usr/share/magus/docs/image/Bedienung/Buttons/Welc_Button_Load.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Grad.png
/usr/share/magus/docs/image/Bedienung/Buttons/GW_Button_Eigenschaften.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Zauber.png
/usr/share/magus/docs/image/Bedienung/Buttons/ZG-Button-Modify.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-EP-Eingabe.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Save.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Print.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Win-Button-Geld.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Geld-in.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Neu.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Ausdauer.png
/usr/share/magus/docs/image/Bedienung/Buttons/ZG-Button-Vorgaben.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Open.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Back.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-Ruest.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Zaub-All.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-WinButton-Eigenschaft.png
/usr/share/magus/docs/image/Bedienung/Buttons/GW_Win_Button_WerteEdit.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Eigenschaft.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Anleit.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-Waffen.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Resist.png
/usr/share/magus/docs/image/Bedienung/Buttons/Button_Forward.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-Beruf.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Info.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Buttton-Steigern.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Zaub-Dice.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Win-Button-Ausruest.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Win-Button-Ruest.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Win-Button-AngebFert.png
/usr/share/magus/docs/image/Bedienung/Buttons/ZG-Button-Steigern.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Win-Button-LPunkte.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-Zaub-Salz.png
/usr/share/magus/docs/image/Bedienung/Buttons/ZG-Button-G1-erzeugen.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Button-LP-Transfer.png
/usr/share/magus/docs/image/Bedienung/Buttons/St-Button-SelbstStud.png
/usr/share/magus/docs/image/Bedienung/Buttons/LS-Win-Button-Beruf.png
/usr/share/magus/docs/image/Bedienung/Buttons/GW_Button_WerteEdit.png
/usr/share/magus/docs/image/Bedienung/Buttons/Win_Button_Exit.png
/usr/share/magus/docs/image/Bedienung/Opt-View/P-Button-nur-Icon.png
/usr/share/magus/docs/image/Bedienung/Opt-View/P-Button-nur-Text.png
/usr/share/magus/docs/image/Bedienung/Opt-View/Button-Icon-u-Text.png
/usr/share/magus/docs/image/Bedienung/Opt-View/Reiter-Icon-u-Text.png
/usr/share/magus/docs/image/Bedienung/Opt-View/Button-nur-Icon.png
/usr/share/magus/docs/image/Bedienung/Opt-View/Reiter-nur-Icon.png
/usr/share/magus/docs/image/Bedienung/Opt-View/Reiter-nur-Text.png
/usr/share/magus/docs/image/Bedienung/Opt-View/P-Button-Text-u-Icon.png
/usr/share/magus/docs/image/Bedienung/module/DS-66.png
/usr/share/magus/docs/image/Bedienung/module/Welcome.png
/usr/share/magus/docs/image/Bedienung/module/GW-66.png
/usr/share/magus/docs/image/Bedienung/module/ZG-66.png
/usr/share/magus/docs/image/Bedienung/module/NG-66.png
/usr/share/magus/docs/image/Bedienung/module/OP-66.png
/usr/share/magus/docs/image/Bedienung/module/AU-66.png
/usr/share/magus/docs/image/Bedienung/module/St-66.png
/usr/share/magus/docs/image/Bedienung/module/LS-66.png
/usr/share/magus/docs/image/Bedienung/Notebook/St-Notebook-Besitz.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook_Ausruestung.png
/usr/share/magus/docs/image/Bedienung/Notebook/Win_Notebook_Zufall.png
/usr/share/magus/docs/image/Bedienung/Notebook/St-Notebook-SprachUSchrift.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook_Geschichte.png
/usr/share/magus/docs/image/Bedienung/Notebook/Win_Notebook_Geschichte.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook_Grundwerte.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook-Waffen.png
/usr/share/magus/docs/image/Bedienung/Notebook/St-Notebook-Fertigk.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook_Optionen.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook_Zufall.png
/usr/share/magus/docs/image/Bedienung/Notebook/St-Notebook-Waffen.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook_Steigern.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook_Beschreibung.png
/usr/share/magus/docs/image/Bedienung/Notebook/Win_Notebook_Grundwerte.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook_Info.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook-SprachUSchrift.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook-Zauber.png
/usr/share/magus/docs/image/Bedienung/Notebook/Win_Notebook_Optionen.png
/usr/share/magus/docs/image/Bedienung/Notebook/St-Notebook-Zauber.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook_Lernschema.png
/usr/share/magus/docs/image/Bedienung/Notebook/Win_Notebook_Steigern.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook-Besitz.png
/usr/share/magus/docs/image/Bedienung/Notebook/Notebook-Fertigkeiten.png
/usr/share/magus/docs/image/Bedienung/Notebook/Win_Notebook_Lernschema.png
/usr/share/magus/docs/image/Bedienung/Elemente/GW-GenesisBar.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Zau-Buttons.png
/usr/share/magus/docs/image/Bedienung/Elemente/LS-LP-FachKennt-Verw.png
/usr/share/magus/docs/image/Bedienung/Elemente/ZG-Ab-Steigern.png
/usr/share/magus/docs/image/Bedienung/Elemente/NG-News.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Bes-Rue.png
/usr/share/magus/docs/image/Bedienung/Elemente/LS-LernpunktVerwaltung.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-SpraUSchri-Schri.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Waf-GK.png
/usr/share/magus/docs/image/Bedienung/Elemente/Menubar.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-SpraUSchri-Spra.png
/usr/share/magus/docs/image/Bedienung/Elemente/ZG-Ab-Erzeugen.png
/usr/share/magus/docs/image/Bedienung/Elemente/OP-GlobOpt.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Regler-AEP-Geld.png
/usr/share/magus/docs/image/Bedienung/Elemente/NG-Redo-List.png
/usr/share/magus/docs/image/Bedienung/Elemente/Win_NSC-Icon.png
/usr/share/magus/docs/image/Bedienung/Elemente/NG-Fig-List.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-InfoBar.png
/usr/share/magus/docs/image/Bedienung/Elemente/LS-LP-Allgem-Verw.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Waf-WF.png
/usr/share/magus/docs/image/Bedienung/Elemente/ButtonBar.png
/usr/share/magus/docs/image/Bedienung/Elemente/LS-Buttonleiste.png
/usr/share/magus/docs/image/Bedienung/Elemente/OP-Pfade.png
/usr/share/magus/docs/image/Bedienung/Elemente/Statusleiste.png
/usr/share/magus/docs/image/Bedienung/Elemente/LS-Mod-Bar.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-FP-EP.png
/usr/share/magus/docs/image/Bedienung/Elemente/Win_Wizard-Icon.png
/usr/share/magus/docs/image/Bedienung/Elemente/LS-LP-UngewFert-Verw.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Bes-Waf.png
/usr/share/magus/docs/image/Bedienung/Elemente/OP-PDF.png
/usr/share/magus/docs/image/Bedienung/Elemente/GW-Eingabe.png
/usr/share/magus/docs/image/Bedienung/Elemente/OP-Ansicht.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Praxis-mod.png
/usr/share/magus/docs/image/Bedienung/Elemente/Notebook-Tabs.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Zau-ZauMit.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-PP-Eingabe.png
/usr/share/magus/docs/image/Bedienung/Elemente/LS-LP-WaffenFert-Verw.png
/usr/share/magus/docs/image/Bedienung/Elemente/OP-Icons.png
/usr/share/magus/docs/image/Bedienung/Elemente/LS-Auswahlfenster.png
/usr/share/magus/docs/image/Bedienung/Elemente/LS-LP-Zauber-Verw.png
/usr/share/magus/docs/image/Bedienung/Elemente/GW-Werte.png
/usr/share/magus/docs/image/Bedienung/Elemente/OP-Hausregeln.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Modus.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Zau-Zaubern.png
/usr/share/magus/docs/image/Bedienung/Elemente/Wizard-Icon.png
/usr/share/magus/docs/image/Bedienung/Elemente/NSC-Icon.png
/usr/share/magus/docs/image/Bedienung/Elemente/St-Grad-Buttons.png
/usr/share/magus/docs/getitWin.html
/usr/share/magus/docs/TroubFAQ.html
/usr/share/magus/docs/BMod_Be.html
/usr/share/magus/docs/BMod_St_SpraSchri.html
/usr/share/magus/docs/BMod_Op.html
/usr/share/magus/docs/About.html
/usr/share/magus/docs/BMod_Au.html
/usr/share/magus/docs/BMod_Welcome.html
/usr/share/magus/docs/Bedienung_Genesis.html
/usr/share/magus/docs/Trouble.html
/usr/share/magus/docs/index.html
/usr/share/magus/docs/Bedienung_Beschreib.html
/usr/share/magus/docs/BMod_St_Besitz.html
/usr/share/magus/docs/BMod_St_Waf.html
/usr/share/magus/docs/BMod_LS.html
/usr/share/magus/docs/Bedienung_Modul.html
/usr/share/magus/docs/Features.html
/usr/share/magus/docs/VorausWin.html
/usr/share/magus/docs/InstallWin.html
/usr/share/magus/docs/getitLin.html
/usr/share/magus/docs/BGen_ZGen.html
/usr/share/magus/docs/BSTV_Std.html
/usr/share/magus/docs/Bedienung_Steigern.html
/usr/share/magus/docs/BMod_NG.html
/usr/share/magus/docs/BGen_Rule.html
/usr/share/magus/docs/BMod_ZG..html
/usr/share/magus/docs/BedienungMain.html
/usr/share/magus/docs/TroubKomp.html
/usr/share/magus/docs/TroubBug.html
/usr/share/magus/docs/Lizenz.html
/usr/share/magus/docs/BGen_Wizard.html
/usr/share/magus/docs/magus.css
/usr/share/magus/docs/Download.html
/usr/share/magus/docs/BMod_St_Fert.html
/usr/share/magus/docs/BSTV_ZG.html
/usr/share/magus/docs/BMod_GW.html
/usr/share/magus/docs/TroubUse.html
/usr/share/magus/docs/VorausLin.html
/usr/share/magus/docs/InstallLin.html
/usr/share/magus/docs/Bedienung_Element.html
/usr/share/magus/docs/TroubInst.html
/usr/share/magus/docs/BMod_St.html
/usr/share/magus/docs/getit.html
/usr/share/magus/docs/Bedienung_Option.html
/usr/share/magus/Nahuatlan.xml
/usr/share/magus/magus_document_eingabe.tex
/usr/share/magus/Rawindra.xml
/usr/share/magus/KanThaiPan.xml
/usr/share/magus/drache.png
/usr/share/magus/Ikengabecken.xml
/usr/share/magus/Minangpahit.xml
/usr/share/magus/HexenzauberDruidenkraftFinster.xml
/usr/share/magus/Alba.xml
/usr/share/magus/midgard.xml
/usr/share/magus/Kompendium.xml
/usr/share/magus/saebel.png
/usr/share/magus/Gildenbrief.xml
/usr/share/magus/AbenteuerBaende.xml
/usr/share/magus/MeisterDerSphaeren.xml
/usr/share/magus/Money-gray.png
/usr/share/magus/Alba-grey.png
/usr/share/magus/HexenzauberDruidenkraft.xml
/usr/share/magus/schwert.png
/usr/share/magus/BarbarenWutRitterEhre.xml
/usr/share/magus/wurfbeil.png
/usr/share/magus/Kuestenstaaten.xml
/usr/share/magus/Eschar.xml
/usr/share/magus/Waeland.xml
/usr/share/magus/pixmaps/Icons/png/MAGUS_Logo_32x32.png
/usr/share/magus/pixmaps/Icons/png/MAGUS_Logo_48x48.png
/usr/share/magus/pixmaps/Icons/png/MAGUS_Logo_16x16.png
/usr/share/magus/pixmaps/Icons/xpm/MAGUS_Logo_32x32.xpm
/usr/share/magus/pixmaps/Icons/xpm/MAGUS_Logo_48x48.xpm
/usr/share/magus/pixmaps/Icons/xpm/MAGUS_Logo_16x16.xpm
/usr/share/magus/Arkanum.xml
/usr/share/magus/Letter-Feather-grey.png
/usr/share/magus/MAGUS-Logo-grey2.png
/usr/share/magus/Regelwerk3.xml
/usr/share/magus/Regelwerk4.xml
