Summary: MAGUS - Midgard Abenteurer Generieren Und Steigern
Name: magus
Version: 0.8.2pre
Release: 1
Copyright: GPL
Group: application/games
Distribution: SuSE_7.2
Url: midgard.berlios.de
Buildroot: /var/tmp/build-root-%{name}

%description
Dies ist ein Test-RPM PAcket für MAGUS. 
MAGUS ist ein Abenteurer Generierungs- und Steigerungstool für das Fantasyrollenspiel Midgard



%clean





%files
/usr/local/bin/magus
/usr/local/share/magus/AbenteuerBaende.xml 
/usr/local/share/magus/Alba.xml
/usr/local/share/magus/Alba-grey.png
/usr/local/share/magus/Arkanum.xml
/usr/local/share/magus/BarbarenWutRitterEhre.xml
/usr/local/share/magus/Eschar.xml
/usr/local/share/magus/Gildenbrief.xml
/usr/local/share/magus/HexenzauberDruidenkraft.xml
/usr/local/share/magus/HexenzauberDruidenkraftFinster.xml
/usr/local/share/magus/KanThaiPan.xml
/usr/local/share/magus/Kuestenstaaten.xml
/usr/local/share/magus/Letter-Feather-grey.png
/usr/local/share/magus/MAGUS-Logo-grey2.png
/usr/local/share/magus/MAGUS_Logo_Small.xpm
/usr/local/share/magus/MAGUS_Logo_Tiny.xpm
/usr/local/share/magus/MeisterDerSphaeren.xml
/usr/local/share/magus/Minangpahit.xml
/usr/local/share/magus/Nahuatlan.xml
/usr/local/share/magus/Rawindra.xml
/usr/local/share/magus/Regelwerk3.xml
/usr/local/share/magus/Regelwerk4.xml
/usr/local/share/magus/TippsTricks.xml
/usr/local/share/magus/Waeland.xml
/usr/local/share/magus/drache.png
/usr/local/share/magus/magus_document_eingabe.tex
/usr/local/share/magus/midgard.xml
/usr/local/share/magus/midgard_document_eingabe.tex
/usr/local/share/magus/schwert.png
/usr/local/share/magus/wurfbeil.png
/usr/local/share/magus/docs/image/But_AGW.png
/usr/local/share/magus/docs/image/But_CLOSE.png
/usr/local/share/magus/docs/image/Statusbar.png
/usr/local/share/magus/docs/image/But_EDIT.png
/usr/local/share/magus/docs/image/But_GW_W.png
/usr/local/share/magus/docs/image/But_HELP.png
/usr/local/share/magus/docs/image/But_INFO.png
/usr/local/share/magus/docs/image/But_LAND.png
/usr/local/share/magus/docs/image/Stat-NSC.png
/usr/local/share/magus/docs/image/But_LC.png
/usr/local/share/magus/docs/image/But_LaTeX.png
/usr/local/share/magus/docs/image/But_NC.png
/usr/local/share/magus/docs/image/But_SC.png
/usr/local/share/magus/docs/image/But_Spezies.png
/usr/local/share/magus/docs/image/But_TYP.png
/usr/local/share/magus/docs/image/But_HELP-HTML.png
/usr/local/share/magus/docs/image/OPT-Ansicht.png
/usr/local/share/magus/docs/image/OPT-Global.png
/usr/local/share/magus/docs/image/OPT-Other.png
/usr/local/share/magus/docs/image/GW-Werte.png
/usr/local/share/magus/docs/image/OPT-Printing.png
/usr/local/share/magus/docs/image/Optionen-66.png
/usr/local/share/magus/docs/image/TAB_Descr.png
/usr/local/share/magus/docs/image/TAB-GW+TXT.png
/usr/local/share/magus/docs/image/LS-Geld-W-in.png
/usr/local/share/magus/docs/image/TAB-GW.png
/usr/local/share/magus/docs/image/TAB-Lern.png
/usr/local/share/magus/docs/image/TAB-Steigern.png
/usr/local/share/magus/docs/image/Ausruest-66.png
/usr/local/share/magus/docs/image/But_Dice_Armor.png
/usr/local/share/magus/docs/image/Stat-Wiz.png
/usr/local/share/magus/docs/image/But_LS-F_Angeb.png
/usr/local/share/magus/docs/image/But_Dice_Ausruest.png
/usr/local/share/magus/docs/image/LS-Opt-View.png
/usr/local/share/magus/docs/image/But_LernP-D.png
/usr/local/share/magus/docs/image/But_LernP-E.png
/usr/local/share/magus/docs/image/But_MENU.png
/usr/local/share/magus/docs/image/But_RS.png
/usr/local/share/magus/docs/image/LS-Rue-in.png
/usr/local/share/magus/docs/image/Abwehr.png
/usr/local/share/magus/docs/image/LS-Buttons.png
/usr/local/share/magus/docs/image/LS-Waf-in.png
/usr/local/share/magus/docs/image/OPT-But_Img+Txt.png
/usr/local/share/magus/docs/image/OPT-But_Img.png
/usr/local/share/magus/docs/image/LSchema-66.png
/usr/local/share/magus/docs/image/MAGUS-Logo-Text-halb.png
/usr/local/share/magus/docs/image/Steigern-66.png
/usr/local/share/magus/docs/image/TAB-Ausruest.png
/usr/local/share/magus/docs/image/TAB-LS-Beruf.png
/usr/local/share/magus/docs/image/OPT-But_Txt.png
/usr/local/share/magus/docs/image/OPT-Hausregeln.png
/usr/local/share/magus/docs/image/Tab-Orig-False.png
/usr/local/share/magus/docs/image/LS-Beruf-in.png
/usr/local/share/magus/docs/image/LS_Select_Waf.png
/usr/local/share/magus/docs/image/BUT-ST-PP-Lang.png
/usr/local/share/magus/docs/image/BUT_Beruf_Eingabe.png
/usr/local/share/magus/docs/image/WIN-AngebFert.png
/usr/local/share/magus/docs/image/WIN-Beruf_I.png
/usr/local/share/magus/docs/image/BUT-St-GFP-in.png
/usr/local/share/magus/docs/image/But_Mag_Bon.png
/usr/local/share/magus/docs/image/ST-EP+Geld.png
/usr/local/share/magus/docs/image/MAGUS-Tux-Logo-med.png
/usr/local/share/magus/docs/image/BUT-F-ALLG.png
/usr/local/share/magus/docs/image/BUT-F-FK.png
/usr/local/share/magus/docs/image/BUT-F-UNG.png
/usr/local/share/magus/docs/image/BUT-F-WAF.png
/usr/local/share/magus/docs/image/BUT-F-ZAU.png
/usr/local/share/magus/docs/image/LS-Fert-Select.png
/usr/local/share/magus/docs/image/magus-fav.ico
/usr/local/share/magus/docs/image/MAGUS-Pulldown.png
/usr/local/share/magus/docs/image/MAGUS_Main_Elements.png
/usr/local/share/magus/docs/image/MAGUS_Notebook.png
/usr/local/share/magus/docs/image/TAB_Info.png
/usr/local/share/magus/docs/image/TAB_News.png
/usr/local/share/magus/docs/image/TAB_Opt.png
/usr/local/share/magus/docs/image/But_Redo.png
/usr/local/share/magus/docs/image/But_Undo.png
/usr/local/share/magus/docs/image/GW_Buttons.png
/usr/local/share/magus/docs/image/MAIN_GW.png
/usr/local/share/magus/docs/image/But_Mouse3.png
/usr/local/share/magus/docs/image/But_ST_SRoll.png
/usr/local/share/magus/docs/image/But_Set_Werte.png
/usr/local/share/magus/docs/image/Buttonleiste_Perm.png
/usr/local/share/magus/docs/image/Select_6of9.png
/usr/local/share/magus/docs/image/Select_Geschl.png
/usr/local/share/magus/docs/image/Select_Zuweis.png
/usr/local/share/magus/docs/image/Select_Herk.png
/usr/local/share/magus/docs/image/BUT_LS_Geld.png
/usr/local/share/magus/docs/image/BUT_LS_SpezWaf.png
/usr/local/share/magus/docs/image/BUT_LS_Waf.png
/usr/local/share/magus/docs/image/Win_Geld.png
/usr/local/share/magus/docs/image/Win_Ruest.png
/usr/local/share/magus/docs/image/Win_ST_EP_In.png
/usr/local/share/magus/docs/image/BUT-F-BER.png
/usr/local/share/magus/docs/image/LS_Win_Herk.png
/usr/local/share/magus/docs/image/Win_Select_Waf.png
/usr/local/share/magus/docs/image/ST-Notebook-Lang.png
/usr/local/share/magus/docs/image/ST-Notebook-Waf.png
/usr/local/share/magus/docs/image/ST-Notebook-Zau.png
/usr/local/share/magus/docs/image/ST-Rel-select.png
/usr/local/share/magus/docs/image/ST-Steigern.png
/usr/local/share/magus/docs/image/ST-SteigernZ.png
/usr/local/share/magus/docs/image/ST-Zauber-Spruchrolle.png
/usr/local/share/magus/docs/image/ST_INFO_BES.png
/usr/local/share/magus/docs/image/But-St-Ausd.png
/usr/local/share/magus/docs/image/But-St-EP-In.png
/usr/local/share/magus/docs/image/But-St-Eigen.png
/usr/local/share/magus/docs/image/But-St-Grad-all.png
/usr/local/share/magus/docs/image/But-St-Grad.png
/usr/local/share/magus/docs/image/But-St-High.png
/usr/local/share/magus/docs/image/But-St-Kost.png
/usr/local/share/magus/docs/image/But-St-Mon.png
/usr/local/share/magus/docs/image/But-St-PP-In.png
/usr/local/share/magus/docs/image/But-St-Red.png
/usr/local/share/magus/docs/image/But-St-Res.png
/usr/local/share/magus/docs/image/But-St-Rue.png
/usr/local/share/magus/docs/image/But-St-Unt_Prax.png
/usr/local/share/magus/docs/image/But-St-Unt_Self.png
/usr/local/share/magus/docs/image/But-St-Unt_Unt.png
/usr/local/share/magus/docs/image/But-St-Waf.png
/usr/local/share/magus/docs/image/But-St-Zaub.png
/usr/local/share/magus/docs/image/But-St-kill.png
/usr/local/share/magus/docs/image/But_LS-OPT_zeige_gelernt.png
/usr/local/share/magus/docs/image/But_LS-OPT_zeige_teuer.png
/usr/local/share/magus/docs/image/But_LS-Trans.png
/usr/local/share/magus/docs/image/LS_LP-Wissen_Typ.png
/usr/local/share/magus/docs/image/LS_Select_Mag_SP.png
/usr/local/share/magus/docs/image/MAGUS-Full-66.png
/usr/local/share/magus/docs/image/ST-But-Grad.png
/usr/local/share/magus/docs/image/ST-Input-PP.png
/usr/local/share/magus/docs/image/ST-Kosten-Select.png
/usr/local/share/magus/docs/image/ST-Notebook-Fert.png
/usr/local/share/magus/docs/image/But-ST-Zauber_All.png
/usr/local/share/magus/docs/image/But-ST-Zauber_Salz.png
/usr/local/share/magus/docs/image/But-St-Abw.png
/usr/local/share/magus/docs/image/But-St-Alter.png
/usr/local/share/magus/docs/image/El_Griff.png
/usr/local/share/magus/docs/image/ST-Fert-Art.png
/usr/local/share/magus/docs/image/ST-Fert-EW.png
/usr/local/share/magus/docs/image/ST-Fert-LernK.png
/usr/local/share/magus/docs/image/ST-Fert-Name.png
/usr/local/share/magus/docs/image/ST-Fert-PP.png
/usr/local/share/magus/docs/image/ST-Fert-Regio.png
/usr/local/share/magus/docs/image/ST-Fert-Steigern.png
/usr/local/share/magus/docs/image/ST-Fert-Verl.png
/usr/local/share/magus/docs/image/ST-Fert-Voraus.png
/usr/local/share/magus/docs/image/ST-GFP-In.png
/usr/local/share/magus/docs/image/ST-Notebook-Besitz.png
/usr/local/share/magus/docs/image/ST-PP-selected.png
/usr/local/share/magus/docs/image/ST-Praxis-Sel.png
/usr/local/share/magus/docs/image/ST-Waf-Fert.png
/usr/local/share/magus/docs/image/ST-Waf-GK.png
/usr/local/share/magus/docs/image/ST-Waf-Kosten.png
/usr/local/share/magus/docs/image/ST-Win-Waf-GK.png
/usr/local/share/magus/docs/image/TAB-ST-Besitz.png
/usr/local/share/magus/docs/image/TAB-ST-Lang.png
/usr/local/share/magus/docs/image/TAB-ST-Zau.png
/usr/local/share/magus/docs/image/Tab-St-Fert.png
/usr/local/share/magus/docs/image/ST-Fert-Red.png
/usr/local/share/magus/docs/image/ST-Notebook-All.png
/usr/local/share/magus/docs/image/Stat-Haus.png
/usr/local/share/magus/docs/image/But-St-Eigen-in.png
/usr/local/share/magus/docs/image/0-MagLogo.png
/usr/local/share/magus/docs/image/0-MidLogo.png
/usr/local/share/magus/docs/image/Anpass-trans.png
/usr/local/share/magus/docs/image/Ausruest-50.png
/usr/local/share/magus/docs/image/BugRoll.png
/usr/local/share/magus/docs/image/Disk-Down.png
/usr/local/share/magus/docs/image/Fert_Lesen-sm.png
/usr/local/share/magus/docs/image/Fert_Lesen.png
/usr/local/share/magus/docs/image/Fertig-50.png
/usr/local/share/magus/docs/image/Info-trans.png
/usr/local/share/magus/docs/image/Lang-Script-50.png
/usr/local/share/magus/docs/image/Letter+Feather50.png
/usr/local/share/magus/docs/image/MagusScreen.png
/usr/local/share/magus/docs/image/NewChar-trans.png
/usr/local/share/magus/docs/image/Regio_Hausregel.png
/usr/local/share/magus/docs/image/Rue-50.png
/usr/local/share/magus/docs/image/TuxScreen.png
/usr/local/share/magus/docs/image/Waffen-50.png
/usr/local/share/magus/docs/image/WinScreen.png
/usr/local/share/magus/docs/image/Zauber-50.png
/usr/local/share/magus/docs/image/Zauberstab4.png
/usr/local/share/magus/docs/image/wizzard-trans-50.png
/usr/local/share/magus/docs/image/TAB-ST-Fert.png
/usr/local/share/magus/docs/image/TAB-ST-Waf.png
/usr/local/share/magus/docs/GW_Main.html
/usr/local/share/magus/docs/XML.Versions
/usr/local/share/magus/docs/Menues.html
/usr/local/share/magus/docs/element.html
/usr/local/share/magus/docs/getit.html
/usr/local/share/magus/docs/index.html
/usr/local/share/magus/docs/Optionen.html
/usr/local/share/magus/docs/mem.html
/usr/local/share/magus/docs/create.html
/usr/local/share/magus/docs/voraus2.html
/usr/local/share/magus/docs/bugreport.html
/usr/local/share/magus/docs/L-Schema_Main.html
/usr/local/share/magus/docs/Steigern_Main.html
/usr/local/share/magus/docs/Trouble_Cmp_Lin.html
/usr/local/share/magus/docs/Steigern_Fert.html
/usr/local/share/magus/docs/voraus-l.html
/usr/local/share/magus/docs/voraus-w.html
/usr/local/share/magus/docs/Steigern_Waf.html
/usr/local/share/magus/docs/Steigern_Besitz.html
/usr/local/share/magus/docs/Steigern_Spra.html
/usr/local/share/magus/docs/Steigern_Zaub.html
/usr/local/share/magus/pixmaps/MAGUS_Logo_Small.xpm
