#!/bin/sh

GTKMM1="-r GTKMM1"

login() {
  echo ========= Logging in ======
  echo Bitte zweimal Return drücken
  cvs -d:pserver:anonymous@cvs.ManuProC.berlios.de:/cvsroot/manuproc login
#  cvs -d :pserver:anonymous@anoncvs.gnome.org:/cvs/gnome login
  cvs -d:pserver:anonymous@cvs.midgard.berlios.de:/cvsroot/midgard login
}

checkout() {
  echo ========  ManuProC_Base ========
  cvs -z3 -d:pserver:anonymous@cvs.ManuProC.berlios.de:/cvsroot/manuproc co ManuProC_Base
  
  echo ========== GtkmmAddons ========
  cvs -z3 -d:pserver:anonymous@cvs.midgard.berlios.de:/cvsroot/midgard co $GTKMM1 GtkmmAddons
  
  echo ========  ManuProC_Widgets ========
  cvs -z3 -d:pserver:anonymous@cvs.ManuProC.berlios.de:/cvsroot/manuproc co $GTKMM1 ManuProC_Widgets
  
#  echo =========== Midgard-Postgres ========
#  echo not needed?
#  cvs -z3 -d:pserver:anonymous@cvs.midgard.berlios.de:/cvsroot/midgard co midgard-postgres
  
  echo ============ Magus ========
  cvs -z3 -d:pserver:anonymous@cvs.midgard.berlios.de:/cvsroot/midgard co $GTKMM1 midgard
}

update() {
  echo ========  ManuProC_Base ========
  ( cd ManuProC_Base && cvs -z3 update -dP )
  echo ========== GtkmmAddons ========
  ( cd GtkmmAddons && cvs -z3 update -dP $GTKMM1 )
  echo ========  ManuProC_Widgets ========
  ( cd ManuProC_Widgets && cvs -z3 update -dP $GTKMM1 )
#  echo =========== Midgard-Postgres ========
#  ( cd midgard-postgres && cvs -z3 update -dP )
  echo ============ Magus ========
  ( cd midgard && cvs -z3 update -dP $GTKMM1 )
}

configure() {
  echo ========  ManuProC_Base ========
  ( cd ManuProC_Base && (./autogen.sh $* ; make ) )
  echo ========== GtkmmAddons ========
  ( cd GtkmmAddons && (cd searchcombo ; ./autogen.sh $* ) ; \	
  	 ./autogen.sh $* ; make )
  echo ========  ManuProC_Widgets ========
  ( cd ManuProC_Widgets && ( ./autogen.sh $* ; make ) )
  echo ============ Magus ========
  ( cd midgard && ./autogen.sh $* )
}

configure_if_needed() {
  echo ========  ManuProC_Base ========
  ( cd ManuProC_Base && \
  	(if [ ! -f config.status ] ; then ./autogen.sh $* ; fi ; \
  	 make ) )
  echo ========== GtkmmAddons ========
  ( cd GtkmmAddons && \
  	(if [ ! -f config.status ] ; \
  	 then (cd searchcombo ; ./autogen.sh $* ) ; \
  	     ./autogen.sh $* ; \
  	 fi ; \
  	 make ) )
  echo ========  ManuProC_Widgets ========
  ( cd ManuProC_Widgets && \
  	(if [ ! -f config.status ] ; then ./autogen.sh $* ; fi ; \
  	 make ) )
  echo ============ Magus ========
  ( cd midgard && ./autogen.sh $* )
}

domake() {
  echo ============ Magus ========
  ( cd midgard && make )
}

doinstall() {
#  echo ============ Midgard-PostgreSQL ========
#  ( cd midgard-postgres && make install )
  echo ============ Magus ========
  cd midgard || exit 1
  make install
  echo Wenn --prefix nicht angegeben wurde, brauche ich jetzt das
  echo root Passwort um Midgard nach /usr/local zu kopieren
  su -c 'make install'
}

if [ "_$1" = "_checkout" -o "_$1" = "_co" ] 
then
  login
  checkout
elif [ "_$1" = "_update" ]
then
  update
elif [ "_$1" = "_configure" ]
then
  configure $2 $3 $4 $5 $6 $7 $8 $9
elif [ "_$1" = "_make" ]
then 
  configure_if_needed $2 $3 $4 $5 $6 $7 $8 $9 
  domake
elif [ "_$1" = "_install" ]
then 
  configure_if_needed $2 $3 $4 $5 $6 $7 $8 $9 
  domake
  doinstall
else
  echo "Magus anonymous-CVS Installierer, $Revision: 1.13 $"
  echo
  echo "USAGE: $0 <Befehl> [Argumente]"
  echo "Befehle: checkout co update configure make install"
  echo
  echo "Normale Reihenfolge:  checkout install  oder  update install"
  echo
  echo "Vorsicht die Pakete werden in $PWD ausgepackt"
fi
