// generated 2001/8/29 14:12:47 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/sound/sound_gtk/sound_gtk.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/main_window.hh and./src/main_window.cc

#ifndef _MAIN_WINDOW_GLADE_HH
#  define _MAIN_WINDOW_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/togglebutton.h>
#include "SimpleTree.hh"
#include <gtk--/clist.h>

class main_window_glade : public Gtk::Window
{   
protected:
        
        class Gtk::ScrolledWindow *scrolledwindow_auswahl;
        class Gtk::ToggleButton *kill_on_new_button;
        class Gtk::ToggleButton *togglebutton_repeat;
        class SimpleTree *tree_list;
        class Gtk::CList *clist_playlist;
        
        main_window_glade();
        
        ~main_window_glade();
};
#endif
