/*  Gtk--addons: a collection of gtk-- addons
 *  Copyright (C) 2001 Adolf Petig GmbH & Co. KG, written by Christof Petig
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

// generated 2001/2/8 23:09:38 CET by christof@puck.(none)
// using glademm V0.5_11c
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- close_window.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/window2.hh and./src/window2.cc

#ifndef _WINDOW2_GLADE_HH
#  define _WINDOW2_GLADE_HH

#include <gtk--/window.h>

class window2_glade : public Gtk::Window
{   
protected:
        
        
        window2_glade();
        
        ~window2_glade();
};
#endif
