// generated 2004/5/8 9:27:44 CEST by christof@puck.petig-baender.de
// using glademm V2.6.0_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --image-provider=MagusImage --gtkmmversion 2.4.0 midgard.glade
// for gtk 2.4.0 and gtkmm 2.4.0
//
// Please modify the corresponding derived classes in ./src/BegruessungsWindow.hh and./src/BegruessungsWindow.cc

#ifndef _BEGRUESSUNGSWINDOW_GLADE_HH
#  define _BEGRUESSUNGSWINDOW_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/table.h>

class BegruessungsWindow_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
protected:
        class Gtk::Table * table_buttons;
        
        BegruessungsWindow_glade();
        
        ~BegruessungsWindow_glade();
private:
        virtual void on_button_eingabe_clicked() = 0;
        virtual void on_button_neu_clicked() = 0;
        virtual void on_button_zufall_clicked() = 0;
        virtual void on_button_load_clicked() = 0;
};
#endif
