// generated 2001/12/21 19:28:33 CET by thoma@Tiger.
// using glademm V0.6.2c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.10 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/Berufe_auswahl.hh and./src/Berufe_auswahl.cc

#ifndef _BERUFE_AUSWAHL_GLADE_HH
#  define _BERUFE_AUSWAHL_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/tooltips.h>
#include "SimpleTree.hh"
#include <gtk--/label.h>
#include <gtk--/spinbutton.h>

class Berufe_auswahl_glade : public Gtk::Window
{   
        
        Gtk::Tooltips _tooltips;
protected:
        class SimpleTree *Beruf_tree;
        class Gtk::Label *label_stern_erklaerung;
        class Gtk::SpinButton *spinbutton_wurf;
        class Gtk::Label *label_wuerfel;
        class Gtk::Label *label_kategorie;
        
        Berufe_auswahl_glade();
        
        ~Berufe_auswahl_glade();
};
#endif
