// generated 2001/3/14 22:01:10 CET by thoma@ig23.
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/Berufe_auswahl.cc

#include "config.h"
#include "Berufe_auswahl.hh"
#include <gtk--/label.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/box.h>
#include <gtk--/table.h>

Berufe_auswahl_glade::Berufe_auswahl_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{   
   
   Gtk::Window *Berufe_auswahl = this;
   berufe_clist_auswahl = manage(new class Gtk::CList(5));
   
   Gtk::ScrolledWindow *scrolledwindow5 = manage(new class Gtk::ScrolledWindow());
   close_berufe = manage(new class Gtk::Button("Schließen"));
   
   Gtk::Label *label158 = manage(new class Gtk::Label("Lernpunkte"));
   beruf_auswahl_lernpunkte = manage(new class Gtk::Label("X"));
   
   Gtk::HBox *hbox11 = manage(new class Gtk::HBox(false, 0));
   Gtk::Table *table9 = manage(new class Gtk::Table(3, 3, false));
   berufe_clist_auswahl->set_column_title(0, "Lernpunkte");
   berufe_clist_auswahl->set_column_justification(0, GTK_JUSTIFY_RIGHT);
   berufe_clist_auswahl->set_column_width(0, 80);
   berufe_clist_auswahl->set_column_title(1, "Vorraussetzung");
   berufe_clist_auswahl->set_column_width(1, 80);
   berufe_clist_auswahl->set_column_title(2, "Stand");
   berufe_clist_auswahl->set_column_width(2, 80);
   berufe_clist_auswahl->set_column_title(3, "Beruf");
   berufe_clist_auswahl->set_column_width(3, 80);
   berufe_clist_auswahl->set_column_title(4, "Vorteile");
   berufe_clist_auswahl->set_column_width(4, 80);
   berufe_clist_auswahl->column_titles_show();
   scrolledwindow5->set_policy(GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
   scrolledwindow5->add(*berufe_clist_auswahl);
   label158->set_alignment(0.5, 0.5);
   label158->set_padding(0, 0);
   beruf_auswahl_lernpunkte->set_alignment(0.5, 0.5);
   beruf_auswahl_lernpunkte->set_padding(11, 0);
   hbox11->pack_start(*label158, false, false, 0);
   hbox11->pack_start(*beruf_auswahl_lernpunkte, false, false, 0);
   table9->attach(*scrolledwindow5, 0, 3, 0, 2, GTK_EXPAND|GTK_FILL, GTK_EXPAND|GTK_FILL, 0, 0);
   table9->attach(*close_berufe, 2, 3, 2, 3, 0, 0, 0, 0);
   table9->attach(*hbox11, 0, 1, 2, 3, GTK_FILL, GTK_FILL, 0, 0);
   Berufe_auswahl->set_usize(600, 400);
   Berufe_auswahl->set_title("Berufe");
   Berufe_auswahl->add(*table9);
   berufe_clist_auswahl->show();
   scrolledwindow5->show();
   close_berufe->show();
   label158->show();
   beruf_auswahl_lernpunkte->show();
   hbox11->show();
   table9->show();
   Berufe_auswahl->show();
   berufe_clist_auswahl->select_row.connect(SigC::slot(static_cast<class Berufe_auswahl*>(this), &Berufe_auswahl::on_berufe_clist_auswahl_select_row));
   berufe_clist_auswahl->unselect_row.connect(SigC::slot(static_cast<class Berufe_auswahl*>(this), &Berufe_auswahl::on_berufe_clist_auswahl_unselect_row));
   close_berufe->clicked.connect(SigC::slot(static_cast<class Berufe_auswahl*>(this), &Berufe_auswahl::on_close_berufe_clicked));
}

Berufe_auswahl_glade::~Berufe_auswahl_glade()
{   
}
