// generated 2002/9/16 9:04:28 CEST by thoma@Tiger.(none)
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/frame_globale_optionen.cc

#include "config.h"
#include "frame_globale_optionen.hh"

frame_globale_optionen_glade::frame_globale_optionen_glade(GlademmData *_data
) : Gtk::Frame("Globale Optionen")
{  frame_globale_optionen = this;
   frame_globale_optionen->set_shadow_type(GTK_SHADOW_ETCHED_IN);
   frame_globale_optionen->set_label_align(0,0);
   frame_globale_optionen->show();
}

frame_globale_optionen_glade::~frame_globale_optionen_glade()
{  
}
