// generated 2002/9/16 21:06:54 CEST by thoma@Tiger.(none)
// using glademm V1.1.1c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.10 and gtkmm 1.2.10
//
// Please modify the corresponding derived classes in ./src/frame_icons.cc

#include "config.h"
#include "frame_icons.hh"

frame_icons_glade::frame_icons_glade(GlademmData *_data
) : Gtk::Frame("Icons")
{  frame_icons = this;
   frame_icons->set_shadow_type(GTK_SHADOW_ETCHED_IN);
   frame_icons->set_label_align(0,0);
   frame_icons->show();
}

frame_icons_glade::~frame_icons_glade()
{  
}
