// generated 2002/12/11 19:15:27 CET by christof@puck.petig-baender.de
// using glademm V1.1.3c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gnome2 midgard.glade
// for gtk 2.0.9 and gtkmm 2.0.1
//
// Please modify the corresponding derived classes in ./src/frame_ansicht.hh and./src/frame_ansicht.cc

#ifndef _FRAME_ANSICHT_GLADE_HH
#  define _FRAME_ANSICHT_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/frame.h>

class frame_ansicht_glade : public Gtk::Frame
{  
protected:
        
        class Gtk::Frame *frame_ansicht;
        
        frame_ansicht_glade(GlademmData *_data);
        
        ~frame_ansicht_glade();
};
#endif
