// generated 2002/12/11 19:15:27 CET by christof@puck.petig-baender.de
// using glademm V1.1.3c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gnome2 midgard.glade
// for gtk 2.0.9 and gtkmm 2.0.1
//
// Please modify the corresponding derived classes in ./src/frame_globale_optionen.cc

#include "config.h"
#include "frame_globale_optionen_glade.hh"

frame_globale_optionen_glade::frame_globale_optionen_glade(GlademmData *_data
) : Gtk::Frame("Globale Optionen")
{  frame_globale_optionen = this;
   frame_globale_optionen->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame_globale_optionen->set_label_align(0,0);
   frame_globale_optionen->show();
}

frame_globale_optionen_glade::~frame_globale_optionen_glade()
{  
}
