/*  Midgard Character Generator
 *  Copyright (C) 2001-2002 Malte Thoma
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

// generated 2001/4/23 11:23:23 CEST by thoma@ig23.
// using glademm V0.5_11f_cvs
//
// some glademm convenience functions
//
// DO NOT EDIT THIS FILE !

#include "config.h"
#include "glademm_support.hh"

static std::map<const __STD::string,Gtk::Widget *> glademm_widgets;

Gtk::Widget * glademm_get_Widget(const __STD::string &name)
{   
   
   std::map<const __STD::string,Gtk::Widget *>::iterator i=glademm_widgets.find(name);
   if (i==glademm_widgets.end()) return 0;
   return (*i).second;
}

void glademm_set_Widget(const __STD::string &name, Gtk::Widget *val)
{   glademm_widgets[name]=val;
}
