// generated 2001/3/7 18:06:13 CET by thoma@ig23.
// using glademm V0.5_11f_cvs
//
// some glademm convenience functions
//
// DO NOT EDIT THIS FILE !

#include "config.h"
#include "glademm_support.hh"

static map<const string,Gtk::RadioButton_Helpers::Group> glademm_radiobuttongroups;

Gtk::RadioButton_Helpers::Group & glademm_RadioButtonGroup(const string &name)
{   return glademm_radiobuttongroups[name];;
}

static map<const string,Gtk::RadioMenuItem_Helpers::Group> glademm_radiomenuitemgroups;

Gtk::RadioMenuItem_Helpers::Group & glademm_RadioMenuItemGroup(const string &name)
{   return glademm_radiomenuitemgroups[name];;
}
