// generated 2001/4/7 0:48:42 CEST by thoma@ig23.
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/KiDo_auswahl.hh and./src/KiDo_auswahl.cc

#ifndef _KIDO_AUSWAHL_GLADE_HH
#  define _KIDO_AUSWAHL_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/clist.h>
#include <gtk--/label.h>

class KiDo_auswahl_glade : public Gtk::Window
{   
protected:
        
        class Gtk::CList *clist_kido_auswahl;
        class Gtk::Label *label_kido_techniken;
        
        KiDo_auswahl_glade();
        
        ~KiDo_auswahl_glade();
};
#endif
