// generated 2002/12/11 19:15:22 CET by christof@puck.petig-baender.de
// using glademm V1.1.3c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --gnome2 midgard.glade
// for gtk 2.0.9 and gtkmm 2.0.1
//
// Please modify the corresponding derived classes in ./src/Midgard_Info.hh and./src/Midgard_Info.cc

#ifndef _MIDGARD_INFO_GLADE_HH
#  define _MIDGARD_INFO_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/scrolledwindow.h>
#include <gtkmm/label.h>
#include <gtkmm/frame.h>
#include <gtkmm/progressbar.h>

class Midgard_Info_glade : public Gtk::ScrolledWindow
{  
protected:
        
        class Gtk::ScrolledWindow *Midgard_Info;
        class Gtk::Label *versionsnummer;
        class Gtk::Frame *frame_regionen;
        class Gtk::ProgressBar *progressbar_regionen;
        class Gtk::Frame *frame_datenbank;
        
        Midgard_Info_glade(GlademmData *_data);
        
        ~Midgard_Info_glade();
};
#endif
