// generated 2006/8/14 17:29:56 CEST by christof@vesta.petig-baender.de
// using glademm V2.12.1
//
// DO NOT EDIT THIS FILE ! It was created using
// /home/christof/cvs/glade--/src/glade-- --image-provider=MagusImage --gtkmmversion 2.4.0 midgard.glade
// for gtk 2.10.1 and gtkmm 2.4.0
//
// Please modify the corresponding derived classes in ./src/Midgard_Info.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#include <sigc++/bind.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "Midgard_Info_glade.hh"
#include <gtkmm/image.h>

extern Glib::RefPtr<Gdk::Pixbuf> MagusImage(const std::string &name);

#include <gtkmm/label.h>
#include <gtkmm/box.h>
#include <gtkmm/separator.h>
#include <gtkmm/button.h>
#include <gtkmm/table.h>
#include <gtkmm/frame.h>
#include <gtkmm/viewport.h>
#include <gtkmm/adjustment.h>

Midgard_Info_glade::Midgard_Info_glade(GlademmData *gmm_data
)
{  Midgard_Info = this;
   
   Gtk::Image *pixmap65 = Gtk::manage(new class Gtk::Image(MagusImage("midgard_logo.xpm")));
   Gtk::Label *label340 = Gtk::manage(new class Gtk::Label("MAGUS\n"
		"(Midgard Abenteuerer Generieren Und Steigern)"));
   versionsnummer = Gtk::manage(new class Gtk::Label("Version: 0.9\n"
		"Spirit of Sargon"));
   
   Gtk::Label *label341 = Gtk::manage(new class Gtk::Label("MIDGARD"));
   frame_regionen = Gtk::manage(new class Gtk::Frame());
   
   Gtk::Image *pixmap1 = Gtk::manage(new class Gtk::Image(MagusImage("Zauber-trans-50.xpm")));
   Gtk::Image *pixmap2 = Gtk::manage(new class Gtk::Image(MagusImage("MAGUS_Logo_Small.xpm")));
   Gtk::Image *pixmap131 = Gtk::manage(new class Gtk::Image(MagusImage("Helper-50.xpm")));
   Gtk::Label *label329 = Gtk::manage(new class Gtk::Label("Grafik"));
   Gtk::Label *label327 = Gtk::manage(new class Gtk::Label("Autoren"));
   Gtk::Label *label330 = Gtk::manage(new class Gtk::Label("Alessandro Filippetti\n"
		"Ulf Kaiser"));
   Gtk::Label *label531 = Gtk::manage(new class Gtk::Label("Beim Abtippen der Daten und Testen haben Michael Gruetzki, Nils Richter,\n"
		"Roland Ritthaler Sebastian Horstmann, Joachim Jordan, Stefan Peschl,\n"
		"Sven Rey, Markus Steinberg, Ottmar Zimmer und viele andere geholfen."));
   Gtk::Image *pixmap5 = Gtk::manage(new class Gtk::Image(MagusImage("LoadChar-trans-50.xpm")));
   Gtk::Label *label335 = Gtk::manage(new class Gtk::Label("Magus im Internet"));
   Gtk::Label *label336 = Gtk::manage(new class Gtk::Label("http://midgard.berlios.de"));
   Gtk::Image *pixmap6 = Gtk::manage(new class Gtk::Image(MagusImage("Lang_Script-trans-50.xpm")));
   Gtk::Label *label337 = Gtk::manage(new class Gtk::Label("Kontakt"));
   Gtk::Label *label338 = Gtk::manage(new class Gtk::Label("midgard-general@lists.berlios.de"));
   Gtk::Image *pixmap57 = Gtk::manage(new class Gtk::Image(MagusImage("pinguin.xpm")));
   Gtk::Image *pixmap104 = Gtk::manage(new class Gtk::Image(MagusImage("gnu-haed-trans-32.xpm")));
   Gtk::HBox *hbox56 = Gtk::manage(new class Gtk::HBox(false, 0));
   Gtk::HSeparator *hseparator17 = Gtk::manage(new class Gtk::HSeparator());
   Gtk::Label *label328 = Gtk::manage(new class Gtk::Label("Malte Thoma\n"
		"Christof Petig"));
   Gtk::Label *label401 = Gtk::manage(new class Gtk::Label("MAGUS unterliegt der"));
   Gtk::Button *button13 = Gtk::manage(new class Gtk::Button("General Public License (GPL)"));
   Gtk::Table *table109 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Label *label342 = Gtk::manage(new class Gtk::Label("MAGUS"));
   Gtk::Frame *frame99 = Gtk::manage(new class Gtk::Frame());
   Gtk::Image *pixmap168 = Gtk::manage(new class Gtk::Image(MagusImage("schirm.xpm")));
   Gtk::Table *table149 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Image *pixmap90 = Gtk::manage(new class Gtk::Image(MagusImage("MAGUS-Logo-Text-halb-t3.xpm")));
   Gtk::Table *table167 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Table *table49 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Viewport *viewport33 = Gtk::manage(new class Gtk::Viewport(*manage(new Gtk::Adjustment(0,0,1)), *manage(new Gtk::Adjustment(0,0,1))));
   label340->set_alignment(0,0.5);
   label340->set_justify(Gtk::JUSTIFY_CENTER);
   versionsnummer->set_alignment(0,0.5);
   versionsnummer->set_justify(Gtk::JUSTIFY_CENTER);
   frame_regionen->set_label_align(0,0.5);
   frame_regionen->set_label_widget(*label341);
   label329->set_alignment(0,0.5);
   label329->set_justify(Gtk::JUSTIFY_CENTER);
   label327->set_alignment(0,0.5);
   label327->set_line_wrap(true);
   label330->set_alignment(0,0.5);
   label531->set_alignment(0,0.5);
   label335->set_alignment(0,0.5);
   label335->set_justify(Gtk::JUSTIFY_CENTER);
   label336->set_alignment(0,0.5);
   label336->set_justify(Gtk::JUSTIFY_CENTER);
   label337->set_alignment(0,0.5);
   label337->set_justify(Gtk::JUSTIFY_CENTER);
   label338->set_alignment(0,0.5);
   label338->set_justify(Gtk::JUSTIFY_CENTER);
   hbox56->pack_start(*pixmap57, Gtk::PACK_SHRINK, 0);
   hbox56->pack_start(*pixmap104, Gtk::PACK_SHRINK, 0);
   label328->set_alignment(0,0.5);
   label401->set_alignment(0,0.5);
   label401->set_justify(Gtk::JUSTIFY_CENTER);
   button13->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button13, "Lizenz anzeigen", "");
   table109->set_row_spacings(3);
   table109->set_col_spacings(5);
   table109->attach(*pixmap1, 0, 1, 0, 1, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*pixmap2, 0, 1, 1, 2, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*pixmap131, 0, 1, 2, 3, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label329, 1, 2, 1, 2, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label327, 1, 2, 0, 1, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label330, 2, 3, 1, 2, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label531, 1, 3, 2, 3, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*pixmap5, 0, 1, 4, 5, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label335, 1, 2, 4, 5, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label336, 2, 3, 4, 5, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*pixmap6, 0, 1, 5, 6, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label337, 1, 2, 5, 6, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label338, 2, 3, 5, 6, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*hbox56, 0, 1, 6, 7, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*hseparator17, 0, 3, 3, 4, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label328, 2, 3, 0, 1, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*label401, 1, 2, 6, 7, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table109->attach(*button13, 2, 3, 6, 7, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   frame99->set_label_align(0,0.5);
   frame99->add(*table109);
   frame99->set_label_widget(*label342);
   table149->attach(*pixmap168, 0, 1, 0, 1, Gtk::EXPAND|Gtk::FILL, Gtk::FILL, 0, 0);
   table167->attach(*pixmap90, 0, 1, 0, 2, Gtk::SHRINK, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, 0, 0);
   table49->attach(*pixmap65, 0, 1, 0, 1, Gtk::FILL, Gtk::FILL, 0, 0);
   table49->attach(*label340, 0, 1, 1, 2, Gtk::AttachOptions(), Gtk::AttachOptions(), 5, 5);
   table49->attach(*versionsnummer, 0, 1, 2, 3, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   table49->attach(*frame_regionen, 1, 2, 4, 5, Gtk::FILL, Gtk::FILL, 0, 0);
   table49->attach(*frame99, 0, 1, 4, 5, Gtk::FILL, Gtk::FILL, 0, 0);
   table49->attach(*table149, 0, 1, 3, 4, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   table49->attach(*table167, 1, 2, 0, 4, Gtk::FILL, Gtk::FILL, 0, 0);
   viewport33->set_shadow_type(Gtk::SHADOW_NONE);
   viewport33->add(*table49);
   Midgard_Info->set_shadow_type(Gtk::SHADOW_NONE);
   Midgard_Info->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   Midgard_Info->add(*viewport33);
   pixmap65->show();
   label340->show();
   versionsnummer->show();
   label341->show();
   frame_regionen->show();
   pixmap1->show();
   pixmap2->show();
   pixmap131->show();
   label329->show();
   label327->show();
   label330->show();
   label531->show();
   pixmap5->show();
   label335->show();
   label336->show();
   pixmap6->show();
   label337->show();
   label338->show();
   pixmap57->show();
   pixmap104->show();
   hbox56->show();
   hseparator17->show();
   label328->show();
   label401->show();
   button13->show();
   table109->show();
   label342->show();
   frame99->show();
   pixmap168->show();
   table149->show();
   pixmap90->show();
   table167->show();
   table49->show();
   viewport33->show();
   Midgard_Info->show();
   button13->signal_clicked().connect(SigC::slot(*this, &Midgard_Info_glade::lizenz_anzeigen), false);
}

Midgard_Info_glade::~Midgard_Info_glade()
{  
}
