// generated 2002/5/20 8:42:41 CEST by thoma@Tiger.(none)
// using glademm V0.6.4b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.10 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/midgard_CG.hh and./src/midgard_CG.cc

#ifndef _MIDGARD_CG_GLADE_HH
#  define _MIDGARD_CG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtk--/window.h>
#include <gtk--/tooltips.h>
#include "Midgard_Info.hh"
#include <gtk--/pixmap.h>
#include <gtk--/label.h>
#include "table_grundwerte.hh"
#include "table_lernschema.hh"
#include <gtk--/frame.h>
#include "MidgardBasicTree.hh"
#include <gtk--/table.h>
#include <gtk--/notebook.h>
#include <gtk--/scale.h>
#include <gtk--/checkbutton.h>
#include <gtk--/radiobutton.h>
#include <gtk--/togglebutton.h>
#include <gtk--/spinbutton.h>
#include <gtk--/box.h>
#include <gtk--/clist.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/button.h>
#include <gtk--/toolbar.h>
#include "table_beschreibung.hh"
#include "table_ausruestung.hh"
#include "table_optionen.hh"
#include <gtk--/list.h>
#include "SimpleTree.hh"
#include <gtk--/handlebox.h>
#include <gtk--/menubar.h>

class midgard_CG_glade : public Gtk::Window
{  
        
        GlademmData *_data;
        Gtk::Tooltips _tooltips;
protected:
        class Midgard_Info *Midgard_Info;
        class Gtk::Pixmap *pixmap_original_tux;
        class Gtk::Label *label_notebook_info;
        class Gtk::Pixmap *pixmap_logo;
        class table_grundwerte *table_grundwerte;
        class Gtk::Pixmap *pixmap_notebook_grundwerte;
        class Gtk::Label *label_notebook_grundwerte;
        class table_lernschema *table_lernschema;
        class Gtk::Frame *frame_lernschema;
        class Gtk::Pixmap *pixmap_notebook_lernen;
        class Gtk::Label *label_notebook_lernen;
        class MidgardBasicTree *alte_fert_tree;
        class MidgardBasicTree *neue_fert_tree;
        class MidgardBasicTree *alte_waffen_tree;
        class MidgardBasicTree *neue_waffen_tree;
        class MidgardBasicTree *alte_grund_tree;
        class MidgardBasicTree *neue_grund_tree;
        class MidgardBasicTree *alte_zauber_tree;
        class MidgardBasicTree *neue_zauber_tree;
        class MidgardBasicTree *alte_zaubermittel_tree;
        class MidgardBasicTree *neue_zaubermittel_tree;
        class Gtk::Table *table_magier_steigern;
        class MidgardBasicTree *alte_kido_tree;
        class MidgardBasicTree *neue_kido_tree;
        class Gtk::Pixmap *pixmap_kurai;
        class Gtk::Table *table_kido_steigern;
        class MidgardBasicTree *alte_sprache_tree;
        class MidgardBasicTree *neue_sprache_tree;
        class MidgardBasicTree *alte_schrift_tree;
        class MidgardBasicTree *neue_schrift_tree;
        class Gtk::Notebook *notebook_lernen;
        class Gtk::Label *gfp;
        class Gtk::Label *label_aep;
        class Gtk::Label *label_kep;
        class Gtk::Label *label_zep;
        class Gtk::Label *label_gold;
        class Gtk::Label *label_silber;
        class Gtk::Label *label_kupfer;
        class Gtk::Label *label_EP;
        class Gtk::Label *label_Gold;
        class Gtk::VScale *vscale_EP_Gold;
        class Gtk::CheckButton *checkbutton_EP_Geld;
        class Gtk::RadioButton *radiobutton_selbst;
        class Gtk::RadioButton *radiobutton_praxis;
        class Gtk::RadioButton *radiobutton_unterweisung;
        class Gtk::Frame *frame_lernen_mit;
        class Gtk::RadioButton *radio_spruchrolle_wuerfeln;
        class Gtk::RadioButton *radio_spruchrolle_auto;
        class Gtk::ToggleButton *togglebutton_spruchrolle;
        class Gtk::ToggleButton *togglebutton_alle_zauber;
        class Gtk::ToggleButton *togglebutton_zaubersalze;
        class Gtk::Frame *frame_zauber_zusatz;
        class Gtk::RadioButton *radiobutton_reduzieren;
        class Gtk::RadioButton *radiobutton_verlernen;
        class Gtk::RadioButton *radiobutton_steigern;
        class Gtk::Frame *frame_fertigkeit;
        class Gtk::SpinButton *spinbutton_pp_eingeben;
        class Gtk::ToggleButton *togglebutton_praxispunkte;
        class Gtk::RadioButton *radiobutton_pp_fertigkeit;
        class Gtk::RadioButton *radiobutton_pp_abwehr;
        class Gtk::RadioButton *radiobutton_pp_zauber;
        class Gtk::RadioButton *radiobutton_pp_spezial;
        class Gtk::RadioButton *radiobutton_pp_resistenz;
        class Gtk::VBox *vbox_praxispunkte;
        class Gtk::Frame *frame_praxispunkte;
        class Gtk::CList *clist_landauswahl;
        class Gtk::ScrolledWindow *scrolledwindow_landauswahl;
        class Gtk::Button *button_grad_zaubern;
        class Gtk::Label *label_resistenz_GFP;
        class Gtk::Label *label_zauber_GFP;
        class Gtk::Label *label_abwehr_GFP;
        class Gtk::Label *label_ausdauer_GFP;
        class Gtk::Label *label_grad_GFP;
        class Gtk::Table *table_gradsteigern_lang;
        class Gtk::Toolbar *toolbar_steigern_kurz;
        class Gtk::Button *button_steigern_kurz;
        class Gtk::Label *label_s_grad;
        class Gtk::Label *label_s_resistenz;
        class Gtk::Label *label_s_zaubern;
        class Gtk::Label *label_s_abwehr;
        class Gtk::Label *label_alter;
        class Gtk::Label *steigern_typ;
        class Gtk::Label *label_s_ap;
        class Gtk::Label *label_steigertage;
        class Gtk::Label *label_pp_abwehr;
        class Gtk::Label *label_pp_zaubern;
        class Gtk::Frame *frame_pp_zaubern;
        class Gtk::Label *label_pp_resistenz;
        class Gtk::Label *label_pp_spezial;
        class Gtk::Frame *frame_pp_spezial;
        class Gtk::Frame *frame_steigern;
        class Gtk::Pixmap *pixmap_notebook_steigern;
        class Gtk::Label *label_notebook_steigern;
        class table_beschreibung *table_beschreibung;
        class Gtk::Pixmap *pixmap_notebook_beschreibung;
        class Gtk::Label *label_notebook_beschreibung;
        class table_ausruestung *table_ausruestung;
        class Gtk::Pixmap *pixmap_notebook_ausruestung;
        class Gtk::Label *label_notebook_ausruestung;
        class table_optionen *table_optionen;
        class Gtk::Pixmap *pixmap_notebook_optionen;
        class Gtk::Label *label_notebook_optionen;
        class Gtk::List *list_news;
        class SimpleTree *undo_tree;
        class Gtk::Pixmap *pixmap_notebook_news_1;
        class Gtk::Pixmap *pixmap_notebook_news_2;
        class Gtk::Label *label_notebook_news;
        class Gtk::Notebook *notebook_main;
        class Gtk::Toolbar *toolbar_top;
        class Gtk::Button *button_undo;
        class Gtk::Button *button_redo;
        class Gtk::HandleBox *griff_toolbar_top;
        class Gtk::MenuBar *main_menubar;
        class Gtk::HandleBox *handlebox_menu;
        class Gtk::Label *label_status;
        class Gtk::Label *label_wizard;
        class Gtk::HandleBox *handlebox_status;
        
        midgard_CG_glade();
        
        ~midgard_CG_glade();
};
#endif
