// generated 2001/5/15 23:18:16 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/HELP/midgard/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/Midgard_Info.hh and./src/Midgard_Info.cc

#ifndef _MIDGARD_INFO_GLADE_HH
#  define _MIDGARD_INFO_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/label.h>

class Midgard_Info_glade : public Gtk::Window
{   
protected:
        
        class Gtk::Label *versionsnummer;
        
        Midgard_Info_glade();
        
        ~Midgard_Info_glade();
};
#endif
