// generated 2002/2/23 20:15:05 CET by thoma@Tiger.
// using glademm V0.6.2c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.10 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/Sprache_auswahl.hh and./src/Sprache_auswahl.cc

#ifndef _SPRACHE_AUSWAHL_GLADE_HH
#  define _SPRACHE_AUSWAHL_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/label.h>
#include <gtk--/clist.h>

class Sprache_auswahl_glade : public Gtk::Window
{   
protected:
        
        class Gtk::Label *sp_sc_label;
        class Gtk::CList *clist_sp_sc;
        
        Sprache_auswahl_glade();
        
        ~Sprache_auswahl_glade();
};
#endif
