// generated 2002/6/13 18:09:41 CEST by thoma@Tiger.(none)
// using glademm V1.1.0b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.10 and gtkmm 1.2.9
//
// Please modify the corresponding derived classes in ./src/table_lernschema.hh and./src/table_lernschema.cc

#ifndef _TABLE_LERNSCHEMA_GLADE_HH
#  define _TABLE_LERNSCHEMA_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtk--/table.h>
#include <gtk--/tooltips.h>
#include <gtk--/spinbutton.h>
#include <gtk--/radiobutton.h>
#include <gtk--/combo.h>
#include <gtk--/frame.h>
#include "MidgardBasicTree.hh"
#include <gtk--/viewport.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/label.h>
#include <gtk--/button.h>
#include <gtk--/togglebutton.h>
#include <gtk--/entry.h>
#include <gtk--/box.h>
#include <gtk--/handlebox.h>
#include <gtk--/checkbutton.h>
#include <gtk--/eventbox.h>
#include <gtk--/pixmap.h>

class table_lernschema_glade : public Gtk::Table
{  
protected:
        
        Gtk::Tooltips _tooltips;
        class Gtk::Table *table_lernschema;
        class Gtk::SpinButton *spinbutton_fach;
        class Gtk::RadioButton *button_fachkenntnisse;
        class Gtk::SpinButton *spinbutton_allgemein;
        class Gtk::RadioButton *button_allgemeinwissen;
        class Gtk::SpinButton *spinbutton_waffen;
        class Gtk::RadioButton *button_waffen;
        class Gtk::SpinButton *spinbutton_zauber;
        class Gtk::RadioButton *button_zauber;
        class Gtk::SpinButton *spinbutton_unge;
        class Gtk::RadioButton *button_untyp_fertigkeiten;
        class Gtk::Combo *combo_kido_stil;
        class Gtk::RadioButton *button_kido_auswahl;
        class Gtk::Frame *frame_KiDo_lernschema;
        class Gtk::Combo *combo_magier_spezialgebiet;
        class Gtk::Frame *frame_lernpunkte;
        class MidgardBasicTree *tree_gelerntes;
        class Gtk::Viewport *viewport_lernen;
        class Gtk::ScrolledWindow *scrolledwindow_lernen;
        class MidgardBasicTree *Tree_Lernschema_Zusatz;
        class Gtk::Frame *frame_lernschema_zusatz;
        class Gtk::Label *label_lernschma_titel;
        class Gtk::Button *button_angeborene_fert;
        class Gtk::SpinButton *spinbutton_beruf;
        class Gtk::Table *table_berufsprozent;
        class Gtk::Entry *entry_berufsname;
        class Gtk::VBox *vbox_berufsname;
        class Gtk::Label *label_gwr;
        class Gtk::SpinButton *spinbutton_waffen_lernschema;
        class Gtk::Table *table_waffen_lernschema_eingabe;
        class Gtk::Button *button_herkunft;
        class Gtk::Button *button_lernpunkte;
        class Gtk::ToggleButton *togglebutton_lernpunkte_edit;
        class Gtk::Button *button_beruf;
        class Gtk::Button *button_lernschema_geld;
        class Gtk::Button *button_lernschema_waffen;
        class Gtk::Button *button_ruestung;
        class Gtk::HandleBox *handlebox_lernschema;
        class Gtk::Label *fertig_typ;
        class Gtk::Label *label_ruestung_lernschema;
        class Gtk::ToggleButton *togglebutton_spezialwaffe;
        class Gtk::Label *label_herkunft_lernschema;
        class Gtk::CheckButton *togglebutton_teure_anzeigen;
        class Gtk::CheckButton *togglebutton_gelernte_anzeigen;
        class Gtk::EventBox *eventbox_zusatz;
        class Gtk::Table *table_lernschema_121;
        class Gtk::Pixmap *pixmap_dfr3;
        class Gtk::ScrolledWindow *scrolledwindow_dfr3;
        
        table_lernschema_glade(GlademmData *_data);
        
        ~table_lernschema_glade();
};
#endif
