// generated 2005/4/27 10:13:15 CEST by thoma@Tiger.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- --image-provider=MagusImage --gtkmmversion 2.4.0 midgard.glade
// for gtk 2.6.2 and gtkmm 2.4.0
//
// Please modify the corresponding derived classes in ./src/table_lernschema.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "table_lernschema_glade.hh"
#include <gtkmm/image.h>

extern Glib::RefPtr<Gdk::Pixbuf> MagusImage(const std::string &name);

#include <gtkmm/table.h>
#include <gtkmm/label.h>
#include <gtkmm/frame.h>
#include <gtkmm/box.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/paned.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <gtkmm/toolitem.h>
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <gtkmm/separatortoolitem.h>
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#include <gtkmm/adjustment.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#include <gtkmm/toolbar.h>
#include <gtkmm/button.h>
#include <gtkmm/radiobutton.h>
#include <gtkmm/entry.h>
#include <gtkmm/treeview.h>

table_lernschema_glade::table_lernschema_glade(GlademmData *gmm_data
) : Gtk::Table(2, 2, false)
{  table_lernschema = this;
   togglebutton_teure_anzeigen = Gtk::manage(new class Gtk::CheckButton("zu teure Fertigkeiten zeigen"));
   togglebutton_gelernte_anzeigen = Gtk::manage(new class Gtk::CheckButton("Gelernte Fertigkeiten zeigen"));
   
   Gtk::Image *pixmap145 = Gtk::manage(new class Gtk::Image(MagusImage("Angeb_Sicht-32.xpm")));
   Gtk::Table *table132 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Label *label644 = Gtk::manage(new class Gtk::Label("Optionen"));
   Gtk::Frame *frame103 = Gtk::manage(new class Gtk::Frame());
   fertig_typ = Gtk::manage(new class Gtk::Label("label280"));
   
   Gtk::Label *label641 = Gtk::manage(new class Gtk::Label("Abenteurertyp"));
   Gtk::Frame *frame59 = Gtk::manage(new class Gtk::Frame());
   label_ruestung_lernschema = Gtk::manage(new class Gtk::Label("label553"));
   
   Gtk::Label *label642 = Gtk::manage(new class Gtk::Label("Rüstungsklasse"));
   Gtk::Frame *frame101 = Gtk::manage(new class Gtk::Frame());
   Gtk::Image *pixmap122 = Gtk::manage(new class Gtk::Image(MagusImage("Weapon-trans-50.xpm")));
   Gtk::Label *label545 = Gtk::manage(new class Gtk::Label("Spezialwaffe\n"
		"auswählen"));
   Gtk::HBox *hbox61 = Gtk::manage(new class Gtk::HBox(false, 0));
   togglebutton_spezialwaffe = Gtk::manage(new class Gtk::ToggleButton());
   label_herkunft_lernschema = Gtk::manage(new class Gtk::Label("label553"));
   
   Gtk::Label *label643 = Gtk::manage(new class Gtk::Label("Herkunft"));
   Gtk::Frame *frame102 = Gtk::manage(new class Gtk::Frame());
   Gtk::Table *table131 = Gtk::manage(new class Gtk::Table(2, 2, false));
   eventbox_zusatz = Gtk::manage(new class Gtk::EventBox());
   table_lernschema_121 = Gtk::manage(new class Gtk::Table(2, 2, false));
   
   Gtk::Label *label544 = Gtk::manage(new class Gtk::Label("Gelernt"));
   tree_gelerntes = new class MidgardBasicTree(MidgardBasicTree::GELERNTES);
   
   Gtk::ScrolledWindow *scrolledwindow73 = Gtk::manage(new class Gtk::ScrolledWindow());
   togglebutton_gelernt_verlernen = Gtk::manage(new class Gtk::ToggleButton("Verlernen"));
   
   Gtk::Table *table122 = Gtk::manage(new class Gtk::Table(2, 2, false));
   scrolledwindow_lernen = Gtk::manage(new class Gtk::ScrolledWindow());
   Tree_Lernschema_Zusatz = new class MidgardBasicTree(MidgardBasicTree::LERNSCHEMAZUSATZ);
   
   Gtk::ScrolledWindow *scrolledwindow77 = Gtk::manage(new class Gtk::ScrolledWindow());
   checkbutton_einschraenkungen_zusatz = Gtk::manage(new class Gtk::CheckButton("Einschränkungen aufheben"));
   
   Gtk::Table *table163 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Label *label645 = Gtk::manage(new class Gtk::Label("Titel"));
   frame_lernschema_zusatz = Gtk::manage(new class Gtk::Frame());
   label_lernschma_titel = Gtk::manage(new class Gtk::Label("label547"));
   
   Gtk::Table *table123 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::HPaned *hpaned6 = Gtk::manage(new class Gtk::HPaned());
   Gtk::Image *button_herkunft_img = Gtk::manage(new class Gtk::Image(MagusImage("CountrChar-trans-50.xpm")));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_herkunft = Gtk::manage(new class Gtk::ToolButton(*button_herkunft_img, "Herkunft"));
#endif //
   
   Gtk::Image *pixmap170 = Gtk::manage(new class Gtk::Image(MagusImage("Angeb_All-32.xpm")));
   Gtk::Label *label537 = Gtk::manage(new class Gtk::Label("angeborene Fertigkeiten"));
   Gtk::VBox *vbox62 = Gtk::manage(new class Gtk::VBox(false, 0));
   button_angeborene_fert = Gtk::manage(new class Gtk::Button());
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   
   Gtk::ToolItem *toolitem12 = Gtk::manage(new class Gtk::ToolItem());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   Gtk::SeparatorToolItem *separatortoolitem3 = Gtk::manage(new class Gtk::SeparatorToolItem());
#endif //
   Gtk::Image *togglebutton_lernpunkte_edit_img = Gtk::manage(new class Gtk::Image(MagusImage("Dice-2W6-trans-50.xpm")));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   togglebutton_lernpunkte_edit = Gtk::manage(new class Gtk::ToggleToolButton(*togglebutton_lernpunkte_edit_img, "Lernpunkte"));
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   
   Gtk::SeparatorToolItem *separatortoolitem4 = Gtk::manage(new class Gtk::SeparatorToolItem());
#endif //
   Gtk::Image *button_beruf_img = Gtk::manage(new class Gtk::Image(MagusImage("Job-trans-50.xpm")));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_beruf = Gtk::manage(new class Gtk::ToolButton(*button_beruf_img, "Beruf"));
#endif //
   
   Gtk::Label *label557 = Gtk::manage(new class Gtk::Label("%Wurf für\n"
		"Beruf eingeben"));
   Gtk::Label *label558 = Gtk::manage(new class Gtk::Label("%"));
   Gtk::Adjustment *spinbutton_beruf_adj = Gtk::manage(new class Gtk::Adjustment(1, 1, 100, 1, 10, 10));
   spinbutton_beruf = Gtk::manage(new class Gtk::SpinButton(*spinbutton_beruf_adj, 1, 0));
   table_berufsprozent = Gtk::manage(new class Gtk::Table(2, 2, false));
   
   Gtk::Label *label542 = Gtk::manage(new class Gtk::Label("Berufsnamen eingeben"));
   entry_berufsname = Gtk::manage(new class Gtk::Entry());
   vbox_berufsname = Gtk::manage(new class Gtk::VBox(false, 0));
   
   Gtk::VBox *vbox49 = Gtk::manage(new class Gtk::VBox(false, 0));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   Gtk::ToolItem *toolitem13 = Gtk::manage(new class Gtk::ToolItem());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   Gtk::SeparatorToolItem *separatortoolitem5 = Gtk::manage(new class Gtk::SeparatorToolItem());
#endif //
   Gtk::Image *button_lernschema_geld_img = Gtk::manage(new class Gtk::Image(MagusImage("Money-50.xpm")));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_lernschema_geld = Gtk::manage(new class Gtk::ToolButton(*button_lernschema_geld_img, "Geld"));
#endif //
   
   Gtk::Image *button_lernschema_waffen_img = Gtk::manage(new class Gtk::Image(MagusImage("Weapon-trans-50.xpm")));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_lernschema_waffen = Gtk::manage(new class Gtk::ToolButton(*button_lernschema_waffen_img, "Waffen"));
#endif //
   label_gwr = Gtk::manage(new class Gtk::Label("%Wurf\n"
		"eingeben"));
   
   Gtk::Adjustment *spinbutton_waffen_lernschema_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 100, 1, 10, 10));
   spinbutton_waffen_lernschema = Gtk::manage(new class Gtk::SpinButton(*spinbutton_waffen_lernschema_adj, 1, 0));
   table_waffen_lernschema_eingabe = Gtk::manage(new class Gtk::Table(2, 2, false));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   
   Gtk::ToolItem *toolitem14 = Gtk::manage(new class Gtk::ToolItem());
#endif //
   Gtk::Image *button_ruestung_img = Gtk::manage(new class Gtk::Image(MagusImage("Dice_Armor-trans-50.xpm")));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_ruestung = Gtk::manage(new class Gtk::ToolButton(*button_ruestung_img, "Rüstung"));
#endif //
   
   Gtk::Image *button_ausruestung_img = Gtk::manage(new class Gtk::Image(MagusImage("Dice-Ausruest-50.xpm")));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_ausruestung = Gtk::manage(new class Gtk::ToolButton(*button_ausruestung_img, "Ausrüstung"));
#endif //
   
   Gtk::Toolbar *toolbar3 = Gtk::manage(new class Gtk::Toolbar());
   handlebox_lernschema = Gtk::manage(new class Gtk::HandleBox());
   
   Gtk::Image *pixmap70 = Gtk::manage(new class Gtk::Image(MagusImage("right_arr-exp3.xpm")));
   Gtk::Button *button_waffe_trans = Gtk::manage(new class Gtk::Button());
   Gtk::Image *pixmap71 = Gtk::manage(new class Gtk::Image(MagusImage("left_arr-exp3.xpm")));
   Gtk::Button *button_fach_trans = Gtk::manage(new class Gtk::Button());
   Gtk::Adjustment *spinbutton_fach_adj = Gtk::manage(new class Gtk::Adjustment(4, 0, 95, 1, 10, 10));
   spinbutton_fach = Gtk::manage(new class Gtk::SpinButton(*spinbutton_fach_adj, 1, 0));
   
   Gtk::Image *pixmap119 = Gtk::manage(new class Gtk::Image(MagusImage("Fert_Laufen-32.xpm")));
   Gtk::Image *pixmap118 = Gtk::manage(new class Gtk::Image(MagusImage("Regio_Alba-50.xpm")));
   Gtk::Image *pixmap120 = Gtk::manage(new class Gtk::Image(MagusImage("Fert_Reiten-32.xpm")));
   Gtk::HBox *hbox60 = Gtk::manage(new class Gtk::HBox(false, 0));
   Gtk::RadioButton::Group _RadioBGroup_button_fachkenntnisse;
   button_fachkenntnisse = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_button_fachkenntnisse));
   
   Gtk::VBox *vbox33 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Label *label635 = Gtk::manage(new class Gtk::Label("Fachkenntnisse"));
   Gtk::Frame *frame25 = Gtk::manage(new class Gtk::Frame());
   Gtk::Adjustment *spinbutton_allgemein_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 95, 1, 10, 10));
   spinbutton_allgemein = Gtk::manage(new class Gtk::SpinButton(*spinbutton_allgemein_adj, 1, 0));
   
   Gtk::Image *pixmap116 = Gtk::manage(new class Gtk::Image(MagusImage("Skills-trans-50.xpm")));
   Gtk::Image *pixmap149 = Gtk::manage(new class Gtk::Image(MagusImage("Fert_Lesen-32.xpm")));
   Gtk::HBox *hbox59 = Gtk::manage(new class Gtk::HBox(false, 0));
   button_allgemeinwissen = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_button_fachkenntnisse));
   
   Gtk::VBox *vbox34 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Label *label636 = Gtk::manage(new class Gtk::Label("Allgemeinwissen"));
   Gtk::Frame *frame26 = Gtk::manage(new class Gtk::Frame());
   Gtk::Adjustment *spinbutton_unge_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 95, 1, 10, 10));
   spinbutton_unge = Gtk::manage(new class Gtk::SpinButton(*spinbutton_unge_adj, 1, 0));
   
   Gtk::Image *pixmap114 = Gtk::manage(new class Gtk::Image(MagusImage("Fert-Gaukler-32.xpm")));
   Gtk::Image *pixmap121 = Gtk::manage(new class Gtk::Image(MagusImage("Angeb_Tast-32.xpm")));
   Gtk::HBox *hbox50 = Gtk::manage(new class Gtk::HBox(false, 0));
   button_untyp_fertigkeiten = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_button_fachkenntnisse));
   
   Gtk::VBox *vbox35 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Label *label637 = Gtk::manage(new class Gtk::Label("Ungewöhnl. Fertigk."));
   Gtk::Frame *frame80 = Gtk::manage(new class Gtk::Frame());
   combo_kido_stil = Gtk::manage(new class Gtk::Combo());
   
   Gtk::Image *pixmap102 = Gtk::manage(new class Gtk::Image(MagusImage("KiDo-trans-50.xpm")));
   Gtk::Label *label540 = Gtk::manage(new class Gtk::Label("KiDo Techniken\n"
		"auswählen"));
   Gtk::HBox *hbox54 = Gtk::manage(new class Gtk::HBox(false, 0));
   button_kido_auswahl = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_button_fachkenntnisse));
   
   Gtk::VBox *vbox45 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Label *label638 = Gtk::manage(new class Gtk::Label("KiDo"));
   frame_KiDo_lernschema = Gtk::manage(new class Gtk::Frame());
   
   Gtk::Adjustment *spinbutton_waffen_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 95, 1, 10, 10));
   spinbutton_waffen = Gtk::manage(new class Gtk::SpinButton(*spinbutton_waffen_adj, 1, 0));
   
   Gtk::Image *pixmap107 = Gtk::manage(new class Gtk::Image(MagusImage("Claymore-50.xpm")));
   Gtk::Image *pixmap100 = Gtk::manage(new class Gtk::Image(MagusImage("Weapon-trans-50.xpm")));
   Gtk::HBox *hbox52 = Gtk::manage(new class Gtk::HBox(false, 0));
   button_waffen = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_button_fachkenntnisse));
   
   Gtk::VBox *vbox36 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Label *label639 = Gtk::manage(new class Gtk::Label("Waffen"));
   Gtk::Frame *frame27 = Gtk::manage(new class Gtk::Frame());
   Gtk::Adjustment *spinbutton_zauber_adj = Gtk::manage(new class Gtk::Adjustment(1, 0, 95, 1, 10, 10));
   spinbutton_zauber = Gtk::manage(new class Gtk::SpinButton(*spinbutton_zauber_adj, 1, 0));
   
   Gtk::Image *pixmap101 = Gtk::manage(new class Gtk::Image(MagusImage("Zauber-trans-50.xpm")));
   Gtk::Image *pixmap123 = Gtk::manage(new class Gtk::Image(MagusImage("Regio_Arkanum-50.xpm")));
   Gtk::HBox *hbox53 = Gtk::manage(new class Gtk::HBox(false, 0));
   button_zauber = Gtk::manage(new class Gtk::RadioButton(_RadioBGroup_button_fachkenntnisse));
   
   Gtk::VBox *vbox37 = Gtk::manage(new class Gtk::VBox(false, 0));
   Gtk::Label *label640 = Gtk::manage(new class Gtk::Label("Zauber"));
   Gtk::Frame *frame28 = Gtk::manage(new class Gtk::Frame());
   combo_magier_spezialgebiet = Gtk::manage(new class Gtk::Combo());
   
   Gtk::Table *table96 = Gtk::manage(new class Gtk::Table(2, 2, false));
   Gtk::Label *label634 = Gtk::manage(new class Gtk::Label("Lernpunkte für"));
   frame_lernpunkte = Gtk::manage(new class Gtk::Frame());
   
   Gtk::Table *table117 = Gtk::manage(new class Gtk::Table(2, 2, false));
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*button_herkunft);
#else //
   
   
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("Herkunft", *button_herkunft_img, Gtk::Toolbar_Helpers::Callback0()));
   button_herkunft = static_cast<Gtk::Button *>(toolbar3->tools().back().get_widget());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*toolitem12);
#else //
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::Element(*button_angeborene_fert));
   
   Gtk::Widget *toolitem12 = toolbar3->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*separatortoolitem3);
#else //
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::Space());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*togglebutton_lernpunkte_edit);
#else //
   
   
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::ToggleElem("Lernpunkte", *togglebutton_lernpunkte_edit_img, Gtk::Toolbar_Helpers::Callback0()));
   togglebutton_lernpunkte_edit = static_cast<Gtk::ToggleButton *>(toolbar3->tools().back().get_widget());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*separatortoolitem4);
#else //
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::Space());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*button_beruf);
#else //
   
   
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("Beruf", *button_beruf_img, Gtk::Toolbar_Helpers::Callback0()));
   button_beruf = static_cast<Gtk::Button *>(toolbar3->tools().back().get_widget());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*toolitem13);
#else //
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::Element(*vbox49));
   
   Gtk::Widget *toolitem13 = toolbar3->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*separatortoolitem5);
#else //
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::Space());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*button_lernschema_geld);
#else //
   
   
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("Geld", *button_lernschema_geld_img, Gtk::Toolbar_Helpers::Callback0()));
   button_lernschema_geld = static_cast<Gtk::Button *>(toolbar3->tools().back().get_widget());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*button_lernschema_waffen);
#else //
   
   
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("Waffen", *button_lernschema_waffen_img, Gtk::Toolbar_Helpers::Callback0()));
   button_lernschema_waffen = static_cast<Gtk::Button *>(toolbar3->tools().back().get_widget());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*toolitem14);
#else //
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::Element(*table_waffen_lernschema_eingabe));
   
   Gtk::Widget *toolitem14 = toolbar3->tools().back().get_widget();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*button_ruestung);
#else //
   
   
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("Rüstung", *button_ruestung_img, Gtk::Toolbar_Helpers::Callback0()));
   button_ruestung = static_cast<Gtk::Button *>(toolbar3->tools().back().get_widget());
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->append(*button_ausruestung);
#else //
   
   
   toolbar3->tools().push_back(Gtk::Toolbar_Helpers::ButtonElem("Ausrüstung", *button_ausruestung_img, Gtk::Toolbar_Helpers::Callback0()));
   button_ausruestung = static_cast<Gtk::Button *>(toolbar3->tools().back().get_widget());
#endif //
   togglebutton_teure_anzeigen->set_flags(Gtk::CAN_FOCUS);
   togglebutton_teure_anzeigen->set_relief(Gtk::RELIEF_NORMAL);
   togglebutton_teure_anzeigen->set_mode(true);
   togglebutton_teure_anzeigen->set_active(false);
   togglebutton_gelernte_anzeigen->set_flags(Gtk::CAN_FOCUS);
   togglebutton_gelernte_anzeigen->set_relief(Gtk::RELIEF_NORMAL);
   togglebutton_gelernte_anzeigen->set_mode(true);
   togglebutton_gelernte_anzeigen->set_active(false);
   pixmap145->set_alignment(0.5,0.5);
   pixmap145->set_padding(0,0);
   table132->set_row_spacings(0);
   table132->set_col_spacings(0);
   table132->attach(*togglebutton_teure_anzeigen, 1, 2, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table132->attach(*togglebutton_gelernte_anzeigen, 1, 2, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table132->attach(*pixmap145, 0, 1, 0, 2, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::FILL, 0, 0);
   label644->set_alignment(0.5,0.5);
   label644->set_padding(0,0);
   label644->set_justify(Gtk::JUSTIFY_LEFT);
   label644->set_line_wrap(false);
   label644->set_use_markup(false);
   label644->set_selectable(false);
   frame103->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame103->set_label_align(0,0.5);
   frame103->add(*table132);
   frame103->set_label_widget(*label644);
   fertig_typ->set_alignment(0.5,0.5);
   fertig_typ->set_padding(5,5);
   fertig_typ->set_justify(Gtk::JUSTIFY_CENTER);
   fertig_typ->set_line_wrap(false);
   fertig_typ->set_use_markup(false);
   fertig_typ->set_selectable(false);
   label641->set_alignment(0.5,0.5);
   label641->set_padding(0,0);
   label641->set_justify(Gtk::JUSTIFY_LEFT);
   label641->set_line_wrap(false);
   label641->set_use_markup(false);
   label641->set_selectable(false);
   frame59->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame59->set_label_align(0,0.5);
   frame59->add(*fertig_typ);
   frame59->set_label_widget(*label641);
   label_ruestung_lernschema->set_alignment(0.5,0.5);
   label_ruestung_lernschema->set_padding(0,0);
   label_ruestung_lernschema->set_justify(Gtk::JUSTIFY_CENTER);
   label_ruestung_lernschema->set_line_wrap(false);
   label_ruestung_lernschema->set_use_markup(false);
   label_ruestung_lernschema->set_selectable(false);
   label642->set_alignment(0.5,0.5);
   label642->set_padding(0,0);
   label642->set_justify(Gtk::JUSTIFY_LEFT);
   label642->set_line_wrap(false);
   label642->set_use_markup(false);
   label642->set_selectable(false);
   frame101->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame101->set_label_align(0,0.5);
   frame101->add(*label_ruestung_lernschema);
   frame101->set_label_widget(*label642);
   pixmap122->set_alignment(0.5,0.5);
   pixmap122->set_padding(0,0);
   label545->set_alignment(0.5,0.5);
   label545->set_padding(0,0);
   label545->set_justify(Gtk::JUSTIFY_CENTER);
   label545->set_line_wrap(false);
   label545->set_use_markup(false);
   label545->set_selectable(false);
   hbox61->pack_start(*pixmap122);
   hbox61->pack_start(*label545, Gtk::PACK_SHRINK, 0);
   togglebutton_spezialwaffe->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*togglebutton_spezialwaffe, "Nach dem Drücken dieses Knopfes kann eine Spezialwaffe gewählt werden. Entweder eine Nahkampfwaffe die 1 LP gekostet hat, oder eine Fernkampfwaffe, die höchstens 2 LP gekostet hat.", "");
   togglebutton_spezialwaffe->set_relief(Gtk::RELIEF_NORMAL);
   togglebutton_spezialwaffe->set_active(false);
   togglebutton_spezialwaffe->add(*hbox61);
   label_herkunft_lernschema->set_alignment(0.5,0.5);
   label_herkunft_lernschema->set_padding(0,0);
   label_herkunft_lernschema->set_justify(Gtk::JUSTIFY_CENTER);
   label_herkunft_lernschema->set_line_wrap(false);
   label_herkunft_lernschema->set_use_markup(false);
   label_herkunft_lernschema->set_selectable(false);
   label643->set_alignment(0.5,0.5);
   label643->set_padding(0,0);
   label643->set_justify(Gtk::JUSTIFY_LEFT);
   label643->set_line_wrap(false);
   label643->set_use_markup(false);
   label643->set_selectable(false);
   frame102->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame102->set_label_align(0,0.5);
   frame102->add(*label_herkunft_lernschema);
   frame102->set_label_widget(*label643);
   table131->set_row_spacings(0);
   table131->set_col_spacings(0);
   table131->attach(*frame59, 0, 1, 0, 1, Gtk::FILL, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, 0, 0);
   table131->attach(*frame101, 2, 3, 0, 1, Gtk::FILL, Gtk::FILL, 0, 0);
   table131->attach(*togglebutton_spezialwaffe, 3, 4, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table131->attach(*frame102, 1, 2, 0, 1, Gtk::FILL, Gtk::FILL, 0, 0);
   eventbox_zusatz->set_events(Gdk::LEAVE_NOTIFY_MASK);
   table_lernschema_121->set_row_spacings(0);
   table_lernschema_121->set_col_spacings(0);
   table_lernschema_121->attach(*frame103, 2, 3, 0, 1, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK, 0, 0);
   table_lernschema_121->attach(*table131, 0, 1, 0, 1, Gtk::SHRINK|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table_lernschema_121->attach(*eventbox_zusatz, 3, 4, 0, 1, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK|Gtk::FILL, 0, 0);
   label544->set_alignment(0,0.5);
   label544->set_padding(0,0);
   label544->set_justify(Gtk::JUSTIFY_CENTER);
   label544->set_line_wrap(false);
   label544->set_use_markup(false);
   label544->set_selectable(false);
   scrolledwindow73->set_shadow_type(Gtk::SHADOW_NONE);
   scrolledwindow73->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   scrolledwindow73->property_window_placement().set_value(Gtk::CORNER_TOP_LEFT);
   scrolledwindow73->add(*tree_gelerntes);
   togglebutton_gelernt_verlernen->set_flags(Gtk::CAN_FOCUS);
   togglebutton_gelernt_verlernen->set_relief(Gtk::RELIEF_NORMAL);
   togglebutton_gelernt_verlernen->set_active(false);
   table122->set_row_spacings(0);
   table122->set_col_spacings(0);
   table122->attach(*label544, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table122->attach(*scrolledwindow73, 0, 2, 1, 2, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, 0, 0);
   table122->attach(*togglebutton_gelernt_verlernen, 1, 2, 0, 1, Gtk::SHRINK, Gtk::SHRINK|Gtk::FILL, 0, 0);
   scrolledwindow_lernen->set_shadow_type(Gtk::SHADOW_NONE);
   scrolledwindow_lernen->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   scrolledwindow_lernen->property_window_placement().set_value(Gtk::CORNER_TOP_LEFT);
   Tree_Lernschema_Zusatz->set_events(Gdk::LEAVE_NOTIFY_MASK);
   scrolledwindow77->set_shadow_type(Gtk::SHADOW_NONE);
   scrolledwindow77->set_policy(Gtk::POLICY_AUTOMATIC, Gtk::POLICY_AUTOMATIC);
   scrolledwindow77->property_window_placement().set_value(Gtk::CORNER_TOP_LEFT);
   scrolledwindow77->add(*Tree_Lernschema_Zusatz);
   checkbutton_einschraenkungen_zusatz->set_flags(Gtk::CAN_FOCUS);
   checkbutton_einschraenkungen_zusatz->set_relief(Gtk::RELIEF_NORMAL);
   checkbutton_einschraenkungen_zusatz->set_mode(true);
   checkbutton_einschraenkungen_zusatz->set_active(false);
   table163->set_row_spacings(0);
   table163->set_col_spacings(0);
   table163->attach(*scrolledwindow77, 0, 1, 1, 2, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, 0, 0);
   table163->attach(*checkbutton_einschraenkungen_zusatz, 0, 1, 0, 1, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   label645->set_alignment(0.5,0.5);
   label645->set_padding(0,0);
   label645->set_justify(Gtk::JUSTIFY_LEFT);
   label645->set_line_wrap(false);
   label645->set_use_markup(false);
   label645->set_selectable(false);
   frame_lernschema_zusatz->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame_lernschema_zusatz->set_label_align(0,0.5);
   frame_lernschema_zusatz->add(*table163);
   frame_lernschema_zusatz->set_label_widget(*label645);
   label_lernschma_titel->set_alignment(0,0.5);
   label_lernschma_titel->set_padding(0,0);
   label_lernschma_titel->set_justify(Gtk::JUSTIFY_CENTER);
   label_lernschma_titel->set_line_wrap(false);
   label_lernschma_titel->set_use_markup(false);
   label_lernschma_titel->set_selectable(false);
   table123->set_row_spacings(0);
   table123->set_col_spacings(0);
   table123->attach(*scrolledwindow_lernen, 0, 1, 1, 2, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, 0, 0);
   table123->attach(*frame_lernschema_zusatz, 1, 2, 0, 2, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, 0, 0);
   table123->attach(*label_lernschma_titel, 0, 1, 0, 1, Gtk::SHRINK, Gtk::SHRINK, 0, 0);
   hpaned6->set_position(243);
   hpaned6->pack1(*table122, Gtk::EXPAND|Gtk::SHRINK);
   hpaned6->pack2(*table123, Gtk::EXPAND|Gtk::SHRINK);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_herkunft->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button_herkunft, "Herkunft, Muttersprache etc.", "");
   button_herkunft->set_visible_horizontal(true);
   button_herkunft->set_visible_vertical(true);
   button_herkunft->set_is_important(false);
   button_herkunft->set_homogeneous(true);
   button_herkunft->set_expand(false);
   button_herkunft->set_tooltip(_tooltips, "Herkunft, Muttersprache etc.");
#endif //
   button_herkunft_img->show();
   pixmap170->set_alignment(0.5,0.5);
   pixmap170->set_padding(0,0);
   label537->set_alignment(0.5,0.5);
   label537->set_padding(0,0);
   label537->set_justify(Gtk::JUSTIFY_CENTER);
   label537->set_line_wrap(false);
   label537->set_use_markup(false);
   label537->set_selectable(false);
   vbox62->pack_start(*pixmap170);
   vbox62->pack_start(*label537);
   button_angeborene_fert->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button_angeborene_fert, "Würfeln bzw. Auswählen", "");
   button_angeborene_fert->set_relief(Gtk::RELIEF_NORMAL);
   button_angeborene_fert->add(*vbox62);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem12->set_visible_horizontal(true);
   toolitem12->set_visible_vertical(true);
   toolitem12->set_is_important(false);
   toolitem12->set_homogeneous(false);
   toolitem12->set_expand(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem12->add(*button_angeborene_fert);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   separatortoolitem3->set_visible_horizontal(true);
   separatortoolitem3->set_visible_vertical(true);
   separatortoolitem3->set_homogeneous(false);
   separatortoolitem3->set_expand(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   togglebutton_lernpunkte_edit->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*togglebutton_lernpunkte_edit, "Lernpunkte würfeln/eingeben (und %Wurf für Berufswahl)", "");
   togglebutton_lernpunkte_edit->set_visible_horizontal(true);
   togglebutton_lernpunkte_edit->set_visible_vertical(true);
   togglebutton_lernpunkte_edit->set_is_important(false);
   togglebutton_lernpunkte_edit->set_homogeneous(true);
   togglebutton_lernpunkte_edit->set_expand(false);
   togglebutton_lernpunkte_edit->set_tooltip(_tooltips, "Lernpunkte würfeln/eingeben (und %Wurf für Berufswahl)");
#endif //
   togglebutton_lernpunkte_edit_img->show();
   togglebutton_lernpunkte_edit->set_active(false);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   separatortoolitem4->set_visible_horizontal(true);
   separatortoolitem4->set_visible_vertical(true);
   separatortoolitem4->set_homogeneous(false);
   separatortoolitem4->set_expand(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_beruf->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button_beruf, "Auswahl aus Originalliste/Berufsnamen selber eingeben.", "");
   button_beruf->set_visible_horizontal(true);
   button_beruf->set_visible_vertical(true);
   button_beruf->set_is_important(false);
   button_beruf->set_homogeneous(true);
   button_beruf->set_expand(false);
   button_beruf->set_tooltip(_tooltips, "Auswahl aus Originalliste/Berufsnamen selber eingeben.");
#endif //
   button_beruf_img->show();
   label557->set_alignment(0,0.5);
   label557->set_padding(0,0);
   label557->set_justify(Gtk::JUSTIFY_CENTER);
   label557->set_line_wrap(false);
   label557->set_use_markup(false);
   label557->set_selectable(false);
   label558->set_alignment(0,0.5);
   label558->set_padding(0,0);
   label558->set_justify(Gtk::JUSTIFY_CENTER);
   label558->set_line_wrap(false);
   label558->set_use_markup(false);
   label558->set_selectable(false);
   spinbutton_beruf->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*spinbutton_beruf, "%Wurf für den Beruf eingeben", "");
   spinbutton_beruf->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbutton_beruf->set_numeric(false);
   spinbutton_beruf->set_digits(0);
   spinbutton_beruf->set_wrap(false);
   table_berufsprozent->set_row_spacings(0);
   table_berufsprozent->set_col_spacings(0);
   table_berufsprozent->attach(*label557, 0, 2, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table_berufsprozent->attach(*label558, 1, 2, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table_berufsprozent->attach(*spinbutton_beruf, 0, 1, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   label542->set_alignment(0,0.5);
   label542->set_padding(0,0);
   label542->set_justify(Gtk::JUSTIFY_LEFT);
   label542->set_line_wrap(false);
   label542->set_use_markup(false);
   label542->set_selectable(false);
   entry_berufsname->set_flags(Gtk::CAN_FOCUS);
   entry_berufsname->set_visibility(true);
   entry_berufsname->set_editable(true);
   entry_berufsname->set_max_length(0);
   entry_berufsname->set_text("");
   entry_berufsname->set_has_frame(true);
   entry_berufsname->set_activates_default(false);
   vbox_berufsname->pack_start(*label542, Gtk::PACK_SHRINK, 0);
   vbox_berufsname->pack_start(*entry_berufsname, Gtk::PACK_SHRINK, 0);
   vbox49->pack_start(*table_berufsprozent);
   vbox49->pack_start(*vbox_berufsname);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem13->set_visible_horizontal(true);
   toolitem13->set_visible_vertical(true);
   toolitem13->set_is_important(false);
   toolitem13->set_homogeneous(false);
   toolitem13->set_expand(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem13->add(*vbox49);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   separatortoolitem5->set_visible_horizontal(true);
   separatortoolitem5->set_visible_vertical(true);
   separatortoolitem5->set_homogeneous(false);
   separatortoolitem5->set_expand(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_lernschema_geld->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button_lernschema_geld, "Geld würfeln/eingeben", "");
   button_lernschema_geld->set_visible_horizontal(true);
   button_lernschema_geld->set_visible_vertical(true);
   button_lernschema_geld->set_is_important(false);
   button_lernschema_geld->set_homogeneous(true);
   button_lernschema_geld->set_expand(false);
   button_lernschema_geld->set_tooltip(_tooltips, "Geld würfeln/eingeben");
#endif //
   button_lernschema_geld_img->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_lernschema_waffen->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button_lernschema_waffen, "Waffen auswürfeln/aussuchen", "");
   button_lernschema_waffen->set_visible_horizontal(true);
   button_lernschema_waffen->set_visible_vertical(true);
   button_lernschema_waffen->set_is_important(false);
   button_lernschema_waffen->set_homogeneous(true);
   button_lernschema_waffen->set_expand(false);
   button_lernschema_waffen->set_tooltip(_tooltips, "Waffen auswürfeln/aussuchen");
#endif //
   button_lernschema_waffen_img->show();
   label_gwr->set_alignment(0,0.5);
   label_gwr->set_padding(0,0);
   label_gwr->set_justify(Gtk::JUSTIFY_CENTER);
   label_gwr->set_line_wrap(false);
   label_gwr->set_use_markup(false);
   label_gwr->set_selectable(false);
   spinbutton_waffen_lernschema->set_flags(Gtk::CAN_FOCUS);
   spinbutton_waffen_lernschema->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbutton_waffen_lernschema->set_numeric(false);
   spinbutton_waffen_lernschema->set_digits(0);
   spinbutton_waffen_lernschema->set_wrap(false);
   table_waffen_lernschema_eingabe->set_row_spacings(0);
   table_waffen_lernschema_eingabe->set_col_spacings(0);
   table_waffen_lernschema_eingabe->attach(*label_gwr, 0, 1, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table_waffen_lernschema_eingabe->attach(*spinbutton_waffen_lernschema, 0, 1, 1, 2, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem14->set_visible_horizontal(true);
   toolitem14->set_visible_vertical(true);
   toolitem14->set_is_important(false);
   toolitem14->set_homogeneous(false);
   toolitem14->set_expand(false);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem14->add(*table_waffen_lernschema_eingabe);
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_ruestung->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button_ruestung, "Rüstung würfeln/aussuchen", "");
   button_ruestung->set_visible_horizontal(true);
   button_ruestung->set_visible_vertical(true);
   button_ruestung->set_is_important(false);
   button_ruestung->set_homogeneous(true);
   button_ruestung->set_expand(false);
   button_ruestung->set_tooltip(_tooltips, "Rüstung würfeln/aussuchen");
#endif //
   button_ruestung_img->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   button_ausruestung->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button_ausruestung, "Ausrüstung aufgrund bestimmter Fertigkeiten würfeln", "");
   button_ausruestung->set_visible_horizontal(true);
   button_ausruestung->set_visible_vertical(true);
   button_ausruestung->set_is_important(false);
   button_ausruestung->set_homogeneous(true);
   button_ausruestung->set_expand(false);
   button_ausruestung->set_tooltip(_tooltips, "Ausrüstung aufgrund bestimmter Fertigkeiten würfeln");
#endif //
   button_ausruestung_img->show();
   toolbar3->set_tooltips(true);
   toolbar3->set_toolbar_style(Gtk::TOOLBAR_BOTH);
   toolbar3->set_orientation(Gtk::ORIENTATION_HORIZONTAL);
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolbar3->set_show_arrow(true);
#endif //
   handlebox_lernschema->set_shadow_type(Gtk::SHADOW_OUT);
   handlebox_lernschema->set_handle_position(Gtk::POS_LEFT);
   handlebox_lernschema->set_snap_edge(Gtk::POS_TOP);
   handlebox_lernschema->add(*toolbar3);
   pixmap70->set_alignment(0.5,0.5);
   pixmap70->set_padding(0,0);
   button_waffe_trans->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button_waffe_trans, "Restpunkte übertragen", "");
   button_waffe_trans->set_relief(Gtk::RELIEF_NONE);
   button_waffe_trans->add(*pixmap70);
   pixmap71->set_alignment(0.5,0.5);
   pixmap71->set_padding(0,0);
   button_fach_trans->set_flags(Gtk::CAN_FOCUS);
   _tooltips.set_tip(*button_fach_trans, "Restpunkte übertragen", "");
   button_fach_trans->set_relief(Gtk::RELIEF_NONE);
   button_fach_trans->add(*pixmap71);
   spinbutton_fach->set_flags(Gtk::CAN_FOCUS);
   spinbutton_fach->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbutton_fach->set_numeric(false);
   spinbutton_fach->set_digits(0);
   spinbutton_fach->set_wrap(false);
   pixmap119->set_alignment(0.5,0.5);
   pixmap119->set_padding(0,0);
   pixmap118->set_alignment(0.5,0.5);
   pixmap118->set_padding(0,0);
   pixmap120->set_alignment(0.5,0.5);
   pixmap120->set_padding(0,0);
   hbox60->pack_start(*pixmap119);
   hbox60->pack_start(*pixmap118);
   hbox60->pack_start(*pixmap120);
   button_fachkenntnisse->set_flags(Gtk::CAN_FOCUS);
   button_fachkenntnisse->set_relief(Gtk::RELIEF_NORMAL);
   button_fachkenntnisse->set_mode(false);
   button_fachkenntnisse->set_active(true);
   button_fachkenntnisse->add(*hbox60);
   vbox33->pack_start(*spinbutton_fach, Gtk::PACK_SHRINK, 0);
   vbox33->pack_start(*button_fachkenntnisse, Gtk::PACK_EXPAND_PADDING, 0);
   label635->set_alignment(0.5,0.5);
   label635->set_padding(0,0);
   label635->set_justify(Gtk::JUSTIFY_LEFT);
   label635->set_line_wrap(false);
   label635->set_use_markup(false);
   label635->set_selectable(false);
   frame25->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame25->set_label_align(0,0.5);
   frame25->add(*vbox33);
   frame25->set_label_widget(*label635);
   spinbutton_allgemein->set_flags(Gtk::CAN_FOCUS);
   spinbutton_allgemein->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbutton_allgemein->set_numeric(false);
   spinbutton_allgemein->set_digits(0);
   spinbutton_allgemein->set_wrap(false);
   pixmap116->set_alignment(0.5,0.5);
   pixmap116->set_padding(0,0);
   pixmap149->set_alignment(0.5,0.5);
   pixmap149->set_padding(0,0);
   hbox59->pack_start(*pixmap116);
   hbox59->pack_start(*pixmap149);
   button_allgemeinwissen->set_flags(Gtk::CAN_FOCUS);
   button_allgemeinwissen->set_relief(Gtk::RELIEF_NORMAL);
   button_allgemeinwissen->set_mode(false);
   button_allgemeinwissen->set_active(false);
   button_allgemeinwissen->add(*hbox59);
   vbox34->pack_start(*spinbutton_allgemein, Gtk::PACK_SHRINK, 0);
   vbox34->pack_start(*button_allgemeinwissen, Gtk::PACK_EXPAND_PADDING, 0);
   label636->set_alignment(0.5,0.5);
   label636->set_padding(0,0);
   label636->set_justify(Gtk::JUSTIFY_LEFT);
   label636->set_line_wrap(false);
   label636->set_use_markup(false);
   label636->set_selectable(false);
   frame26->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame26->set_label_align(0,0.5);
   frame26->add(*vbox34);
   frame26->set_label_widget(*label636);
   spinbutton_unge->set_flags(Gtk::CAN_FOCUS);
   spinbutton_unge->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbutton_unge->set_numeric(false);
   spinbutton_unge->set_digits(0);
   spinbutton_unge->set_wrap(false);
   pixmap114->set_alignment(0.5,0.5);
   pixmap114->set_padding(0,0);
   pixmap121->set_alignment(0.5,0.5);
   pixmap121->set_padding(0,0);
   hbox50->pack_start(*pixmap114);
   hbox50->pack_start(*pixmap121);
   button_untyp_fertigkeiten->set_flags(Gtk::CAN_FOCUS);
   button_untyp_fertigkeiten->set_relief(Gtk::RELIEF_NORMAL);
   button_untyp_fertigkeiten->set_mode(false);
   button_untyp_fertigkeiten->set_active(false);
   button_untyp_fertigkeiten->add(*hbox50);
   vbox35->pack_start(*spinbutton_unge, Gtk::PACK_SHRINK, 0);
   vbox35->pack_start(*button_untyp_fertigkeiten, Gtk::PACK_EXPAND_PADDING, 0);
   label637->set_alignment(0.5,0.5);
   label637->set_padding(0,0);
   label637->set_justify(Gtk::JUSTIFY_LEFT);
   label637->set_line_wrap(false);
   label637->set_use_markup(false);
   label637->set_selectable(false);
   frame80->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame80->set_label_align(0,0.5);
   frame80->add(*vbox35);
   frame80->set_label_widget(*label637);
   combo_kido_stil->get_entry()->set_flags(Gtk::CAN_FOCUS);
   combo_kido_stil->get_entry()->set_visibility(true);
   combo_kido_stil->get_entry()->set_editable(true);
   combo_kido_stil->get_entry()->set_max_length(0);
   combo_kido_stil->get_entry()->set_text("");
   combo_kido_stil->get_entry()->set_has_frame(true);
   combo_kido_stil->get_entry()->set_activates_default(false);
   combo_kido_stil->set_case_sensitive(false);
   {  
      
      const char * const items[] = { "", 0 };
      combo_kido_stil->set_popdown_strings(items);
   }
   combo_kido_stil->get_entry()->set_text("");
   pixmap102->set_alignment(0.5,0.5);
   pixmap102->set_padding(0,0);
   label540->set_alignment(0.5,0.5);
   label540->set_padding(0,0);
   label540->set_justify(Gtk::JUSTIFY_CENTER);
   label540->set_line_wrap(false);
   label540->set_use_markup(false);
   label540->set_selectable(false);
   hbox54->pack_start(*pixmap102, Gtk::PACK_SHRINK, 0);
   hbox54->pack_start(*label540, Gtk::PACK_SHRINK, 0);
   button_kido_auswahl->set_flags(Gtk::CAN_FOCUS);
   button_kido_auswahl->set_relief(Gtk::RELIEF_NORMAL);
   button_kido_auswahl->set_mode(false);
   button_kido_auswahl->set_active(false);
   button_kido_auswahl->add(*hbox54);
   vbox45->pack_start(*combo_kido_stil, Gtk::PACK_SHRINK, 0);
   vbox45->pack_start(*button_kido_auswahl, Gtk::PACK_SHRINK, 0);
   label638->set_alignment(0.5,0.5);
   label638->set_padding(0,0);
   label638->set_justify(Gtk::JUSTIFY_LEFT);
   label638->set_line_wrap(false);
   label638->set_use_markup(false);
   label638->set_selectable(false);
   frame_KiDo_lernschema->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame_KiDo_lernschema->set_label_align(0,0.5);
   frame_KiDo_lernschema->add(*vbox45);
   frame_KiDo_lernschema->set_label_widget(*label638);
   spinbutton_waffen->set_flags(Gtk::CAN_FOCUS);
   spinbutton_waffen->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbutton_waffen->set_numeric(false);
   spinbutton_waffen->set_digits(0);
   spinbutton_waffen->set_wrap(false);
   pixmap107->set_alignment(0.5,0.5);
   pixmap107->set_padding(0,0);
   pixmap100->set_alignment(0.5,0.5);
   pixmap100->set_padding(0,0);
   hbox52->pack_start(*pixmap107);
   hbox52->pack_start(*pixmap100);
   button_waffen->set_flags(Gtk::CAN_FOCUS);
   button_waffen->set_relief(Gtk::RELIEF_NORMAL);
   button_waffen->set_mode(false);
   button_waffen->set_active(false);
   button_waffen->add(*hbox52);
   vbox36->pack_start(*spinbutton_waffen, Gtk::PACK_SHRINK, 0);
   vbox36->pack_start(*button_waffen, Gtk::PACK_EXPAND_PADDING, 0);
   label639->set_alignment(0.5,0.5);
   label639->set_padding(0,0);
   label639->set_justify(Gtk::JUSTIFY_LEFT);
   label639->set_line_wrap(false);
   label639->set_use_markup(false);
   label639->set_selectable(false);
   frame27->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame27->set_label_align(0,0.5);
   frame27->add(*vbox36);
   frame27->set_label_widget(*label639);
   spinbutton_zauber->set_flags(Gtk::CAN_FOCUS);
   spinbutton_zauber->set_update_policy(Gtk::UPDATE_ALWAYS);
   spinbutton_zauber->set_numeric(false);
   spinbutton_zauber->set_digits(0);
   spinbutton_zauber->set_wrap(false);
   pixmap101->set_alignment(0.5,0.5);
   pixmap101->set_padding(0,0);
   pixmap123->set_alignment(0.5,0.5);
   pixmap123->set_padding(0,0);
   hbox53->pack_start(*pixmap101);
   hbox53->pack_start(*pixmap123);
   button_zauber->set_flags(Gtk::CAN_FOCUS);
   button_zauber->set_relief(Gtk::RELIEF_NORMAL);
   button_zauber->set_mode(false);
   button_zauber->set_active(false);
   button_zauber->add(*hbox53);
   vbox37->pack_start(*spinbutton_zauber, Gtk::PACK_SHRINK, 0);
   vbox37->pack_start(*button_zauber, Gtk::PACK_EXPAND_PADDING, 0);
   label640->set_alignment(0.5,0.5);
   label640->set_padding(0,0);
   label640->set_justify(Gtk::JUSTIFY_LEFT);
   label640->set_line_wrap(false);
   label640->set_use_markup(false);
   label640->set_selectable(false);
   frame28->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame28->set_label_align(0,0.5);
   frame28->add(*vbox37);
   frame28->set_label_widget(*label640);
   combo_magier_spezialgebiet->get_entry()->set_flags(Gtk::CAN_FOCUS);
   combo_magier_spezialgebiet->get_entry()->set_visibility(true);
   combo_magier_spezialgebiet->get_entry()->set_editable(true);
   combo_magier_spezialgebiet->get_entry()->set_max_length(0);
   combo_magier_spezialgebiet->get_entry()->set_text("");
   combo_magier_spezialgebiet->get_entry()->set_has_frame(true);
   combo_magier_spezialgebiet->get_entry()->set_activates_default(false);
   combo_magier_spezialgebiet->set_case_sensitive(false);
   {  
      
      const char * const items[] = { "", 0 };
      combo_magier_spezialgebiet->set_popdown_strings(items);
   }
   combo_magier_spezialgebiet->get_entry()->set_text("");
   table96->set_row_spacings(0);
   table96->set_col_spacings(0);
   table96->attach(*button_waffe_trans, 3, 5, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table96->attach(*button_fach_trans, 0, 3, 1, 2, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table96->attach(*frame25, 0, 1, 0, 1, Gtk::FILL, Gtk::EXPAND|Gtk::SHRINK, 0, 0);
   table96->attach(*frame26, 1, 2, 0, 1, Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   table96->attach(*frame80, 2, 4, 0, 1, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   table96->attach(*frame_KiDo_lernschema, 6, 7, 0, 1, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   table96->attach(*frame27, 4, 5, 0, 1, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   table96->attach(*frame28, 5, 6, 0, 1, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   table96->attach(*combo_magier_spezialgebiet, 5, 6, 1, 2, Gtk::AttachOptions(), Gtk::AttachOptions(), 0, 0);
   label634->set_alignment(0.5,0.5);
   label634->set_padding(0,0);
   label634->set_justify(Gtk::JUSTIFY_LEFT);
   label634->set_line_wrap(false);
   label634->set_use_markup(false);
   label634->set_selectable(false);
   frame_lernpunkte->set_shadow_type(Gtk::SHADOW_ETCHED_IN);
   frame_lernpunkte->set_label_align(0,0.5);
   frame_lernpunkte->add(*table96);
   frame_lernpunkte->set_label_widget(*label634);
   table117->set_row_spacings(0);
   table117->set_col_spacings(0);
   table117->attach(*frame_lernpunkte, 0, 1, 0, 1, Gtk::SHRINK, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, 0, 0);
   table_lernschema->set_row_spacings(0);
   table_lernschema->set_col_spacings(0);
   table_lernschema->attach(*table_lernschema_121, 0, 1, 2, 3, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK|Gtk::FILL, 0, 0);
   table_lernschema->attach(*hpaned6, 0, 1, 3, 4, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, Gtk::EXPAND|Gtk::SHRINK|Gtk::FILL, 0, 0);
   table_lernschema->attach(*handlebox_lernschema, 0, 1, 0, 1, Gtk::SHRINK|Gtk::FILL, Gtk::SHRINK|Gtk::FILL, 0, 0);
   table_lernschema->attach(*table117, 0, 1, 1, 2, Gtk::SHRINK|Gtk::FILL, Gtk::AttachOptions(), 0, 0);
   togglebutton_teure_anzeigen->show();
   togglebutton_gelernte_anzeigen->show();
   pixmap145->show();
   table132->show();
   label644->show();
   frame103->show();
   fertig_typ->show();
   label641->show();
   frame59->show();
   label_ruestung_lernschema->show();
   label642->show();
   frame101->show();
   pixmap122->show();
   label545->show();
   hbox61->show();
   togglebutton_spezialwaffe->show();
   label_herkunft_lernschema->show();
   label643->show();
   frame102->show();
   table131->show();
   eventbox_zusatz->show();
   table_lernschema_121->show();
   label544->show();
   tree_gelerntes->show();
   scrolledwindow73->show();
   togglebutton_gelernt_verlernen->show();
   table122->show();
   scrolledwindow_lernen->show();
   Tree_Lernschema_Zusatz->show();
   scrolledwindow77->show();
   checkbutton_einschraenkungen_zusatz->show();
   table163->show();
   label645->show();
   label_lernschma_titel->show();
   table123->show();
   hpaned6->show();
   button_herkunft->show();
   pixmap170->show();
   label537->show();
   vbox62->show();
   button_angeborene_fert->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem12->show();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   separatortoolitem3->show();
#endif //
   togglebutton_lernpunkte_edit->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   separatortoolitem4->show();
#endif //
   button_beruf->show();
   label557->show();
   label558->show();
   spinbutton_beruf->show();
   label542->show();
   entry_berufsname->show();
   vbox49->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem13->show();
#endif //
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   separatortoolitem5->show();
#endif //
   button_lernschema_geld->show();
   button_lernschema_waffen->show();
   label_gwr->show();
   spinbutton_waffen_lernschema->show();
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
   toolitem14->show();
#endif //
   button_ruestung->show();
   button_ausruestung->show();
   toolbar3->show();
   handlebox_lernschema->show();
   pixmap70->show();
   button_waffe_trans->show();
   pixmap71->show();
   button_fach_trans->show();
   spinbutton_fach->show();
   pixmap119->show();
   pixmap118->show();
   pixmap120->show();
   hbox60->show();
   button_fachkenntnisse->show();
   vbox33->show();
   label635->show();
   frame25->show();
   spinbutton_allgemein->show();
   pixmap116->show();
   pixmap149->show();
   hbox59->show();
   button_allgemeinwissen->show();
   vbox34->show();
   label636->show();
   frame26->show();
   spinbutton_unge->show();
   pixmap114->show();
   pixmap121->show();
   hbox50->show();
   button_untyp_fertigkeiten->show();
   vbox35->show();
   label637->show();
   frame80->show();
   combo_kido_stil->show();
   pixmap102->show();
   label540->show();
   hbox54->show();
   button_kido_auswahl->show();
   vbox45->show();
   label638->show();
   frame_KiDo_lernschema->show();
   spinbutton_waffen->show();
   pixmap107->show();
   pixmap100->show();
   hbox52->show();
   button_waffen->show();
   vbox36->show();
   label639->show();
   frame27->show();
   spinbutton_zauber->show();
   pixmap101->show();
   pixmap123->show();
   hbox53->show();
   button_zauber->show();
   vbox37->show();
   label640->show();
   frame28->show();
   combo_magier_spezialgebiet->show();
   table96->show();
   label634->show();
   frame_lernpunkte->show();
   table117->show();
   table_lernschema->show();
   togglebutton_teure_anzeigen->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_togglebutton_teure_anzeigen_toggled), false);
   togglebutton_gelernte_anzeigen->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_togglebutton_gelernte_anzeigen_toggled), false);
   togglebutton_spezialwaffe->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_togglebutton_spezialwaffe_toggled), false);
   eventbox_zusatz->signal_leave_notify_event().connect(SigC::slot(*this, &table_lernschema_glade::on_eventbox_zusatz_leave_notify_event), false);
   tree_gelerntes->signal_leaf_selected().connect(SigC::slot(*this, &table_lernschema_glade::on_tree_gelerntes_leaf_selected));
   checkbutton_einschraenkungen_zusatz->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_togglebutton_einschraenkungen_zusatz_anzeigen_toggled), false);
   button_herkunft->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_herkunftsland_clicked), false);
   button_angeborene_fert->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_button_angeborene_fertigkeit), false);
   togglebutton_lernpunkte_edit->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_togglebutton_lernpunkte_edit_toggled), false);
   button_beruf->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_button_beruf), false);
   spinbutton_beruf->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_beruf_activate), true);
   spinbutton_beruf->signal_focus_in_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_beruf_focus_in), false);
   entry_berufsname->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_entry_berufsname_activate), false);
   button_lernschema_geld->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_button_lernschema_geld), false);
   button_lernschema_waffen->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_button_lernschema_waffen), false);
   spinbutton_waffen_lernschema->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_waffen_lernschema_activate), true);
   spinbutton_waffen_lernschema->signal_focus_in_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_waffen_lernschema_focus_in_event), false);
   button_ruestung->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_button_ruestung), false);
   button_ausruestung->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_button_ausruestung), false);
   button_waffe_trans->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_button_waffe_trans_clicked), false);
   button_fach_trans->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_button_fach_trans_clicked), false);
   spinbutton_fach->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_fach_activate), true);
   spinbutton_fach->signal_focus_out_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_fach_focus_out_event), false);
   spinbutton_fach->signal_focus_in_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_fach_focus_in_event), false);
   button_fachkenntnisse->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_lernliste_wahl_toggled), false);
   spinbutton_allgemein->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_allgemein_activate), true);
   spinbutton_allgemein->signal_focus_out_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_allgemein_focus_out_event), false);
   spinbutton_allgemein->signal_focus_in_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_allgemein_focus_in_event), false);
   button_allgemeinwissen->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_lernliste_wahl_toggled), false);
   spinbutton_unge->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_unge_activate), true);
   spinbutton_unge->signal_focus_out_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_unge_focus_out_event), false);
   spinbutton_unge->signal_focus_in_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_unge_focus_in_event), false);
   button_untyp_fertigkeiten->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_lernliste_wahl_toggled), false);
   combo_kido_stil->get_entry()->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_combo_kido_stil_activate), false);
   combo_kido_stil->get_entry()->signal_focus_out_event().connect(SigC::slot(*this, &table_lernschema_glade::on_combo_kido_stil_focus_out_event), false);
   combo_kido_stil->get_entry()->signal_changed().connect(SigC::slot(*this, &table_lernschema_glade::on_combo_kido_stil_changed), false);
   button_kido_auswahl->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_kido_wahl_clicked), false);
   spinbutton_waffen->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_waffen_activate), true);
   spinbutton_waffen->signal_focus_out_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_waffen_focus_out_event), false);
   spinbutton_waffen->signal_focus_in_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_waffen_focus_in_event), false);
   button_waffen->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_lernliste_wahl_toggled), false);
   button_waffen->signal_clicked().connect(SigC::slot(*this, &table_lernschema_glade::on_button_waffen_clicked), false);
   spinbutton_zauber->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_zaubern_activate), true);
   spinbutton_zauber->signal_focus_out_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_zaubern_focus_out_event), false);
   spinbutton_zauber->signal_focus_in_event().connect(SigC::slot(*this, &table_lernschema_glade::on_spinbutton_zaubern_focus_in_event), false);
   button_zauber->signal_toggled().connect(SigC::slot(*this, &table_lernschema_glade::on_lernliste_wahl_toggled), false);
   combo_magier_spezialgebiet->get_entry()->signal_activate().connect(SigC::slot(*this, &table_lernschema_glade::on_combo_magier_spezialgebiet_activate), false);
   combo_magier_spezialgebiet->get_entry()->signal_focus_out_event().connect(SigC::slot(*this, &table_lernschema_glade::on_combo_magier_spezialgebiet_focus_out_event), false);
   combo_magier_spezialgebiet->get_entry()->signal_changed().connect(SigC::slot(*this, &table_lernschema_glade::on_combo_magier_changed), false);
}

table_lernschema_glade::~table_lernschema_glade()
{  delete tree_gelerntes;
   delete Tree_Lernschema_Zusatz;
}
