// generated 2002/4/16 9:02:34 CEST by thoma@Tiger.(none)
// using glademm V0.6.4b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.10 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/table_optionen.hh and./src/table_optionen.cc

#ifndef _TABLE_OPTIONEN_GLADE_HH
#  define _TABLE_OPTIONEN_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtk--/table.h>
#include "frame_globale_optionen.hh"
#include "frame_drucken.hh"
#include <gtk--/entry.h>

class table_optionen_glade : public Gtk::Table
{  
protected:
        
        class Gtk::Table *table_optionen;
public:
        class frame_globale_optionen *frame_globale_optionen;
        class frame_drucken *frame_drucken;
protected:
        class Gtk::Entry *entry_html;
        class Gtk::Entry *entry_tmp_verz;
        class Gtk::Entry *entry_speicher_verz;
        
        table_optionen_glade(GlademmData *_data);
        
        ~table_optionen_glade();
};
#endif
