// generated 2003/2/24 21:15:40 CET by christof@puck.petig-baender.de
// using glademm V1.1.3e_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- midgard.glade
// for gtk 2.2.1 and gtkmm 2.2.0
//
// Please modify the corresponding derived classes in ./src/table_beschreibung.hh and./src/table_beschreibung.cc

#ifndef _TABLE_BESCHREIBUNG_GLADE_HH
#  define _TABLE_BESCHREIBUNG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/table.h>
#include <gtkmm/tooltips.h>
#include <gtkmm/button.h>
#include <gtkmm/label.h>
#include <gtkmm/spinbutton.h>
#include <gtkmm/textview.h>

class table_beschreibung_glade : public Gtk::Table
{  
protected:
        
        Gtk::Tooltips _tooltips;
        class Gtk::Table *table_beschreibung;
        class Gtk::Button *button_beschreibung_drucken;
        class Gtk::Label *label_grafik;
        class Gtk::Button *button_grafik;
        class Gtk::SpinButton *spinbutton_pix_breite;
        class Gtk::TextView *text_charakter_beschreibung;
        
        table_beschreibung_glade(GlademmData *_data);
        
        ~table_beschreibung_glade();
private:
        virtual void on_button_beschreibung_drucken_clicked() = 0;
        virtual void on_button_grafik_button_release_event() = 0;
        virtual bool on_spinbutton_pix_breite_focus_out_event(GdkEventFocus *ev) = 0;
        virtual bool on_spinbutton_pix_breite_focus_in_event(GdkEventFocus *ev) = 0;
        virtual bool on_text_charakter_beschreibung_focus_out_event(GdkEventFocus *ev) = 0;
        virtual void on_button_fett_clicked() = 0;
        virtual void on_button_kursiv_clicked() = 0;
        virtual void on_button_liste_clicked() = 0;
        virtual void on_button_liste2_clicked() = 0;
};
#endif
