// generated 2001/4/19 8:46:44 CEST by thoma@ig23.
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/Waffen_auswahl.hh and./src/Waffen_auswahl.cc

#ifndef _WAFFEN_AUSWAHL_GLADE_HH
#  define _WAFFEN_AUSWAHL_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/clist.h>
#include <gtk--/label.h>

class Waffen_auswahl_glade : public Gtk::Window
{   
protected:
        
        class Gtk::CList *waffen_clist_auswahl;
        class Gtk::Label *waffen_auswahl_lernpunkte;
        
        Waffen_auswahl_glade();
        
        ~Waffen_auswahl_glade();
};
#endif
