// generated 2001/5/3 22:45:19 CEST by thoma@linux.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// /home/thoma/petig/cvs/christof/glade--/src/glade-- midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/WindowInfo.hh and./src/WindowInfo.cc

#ifndef _WINDOWINFO_GLADE_HH
#  define _WINDOWINFO_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/label.h>
#include <gtk--/button.h>

class WindowInfo_glade : public Gtk::Window
{   
protected:
        
        class Gtk::Label *infotext;
        class Gtk::Button *button_info_ok;
        
        WindowInfo_glade();
        
        ~WindowInfo_glade();
};
#endif
