// generated 2001/5/14 14:50:20 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/Window_doppelcharaktere.hh and./src/Window_doppelcharaktere.cc

#ifndef _WINDOW_DOPPELCHARAKTERE_GLADE_HH
#  define _WINDOW_DOPPELCHARAKTERE_GLADE_HH

#include <gtk--/window.h>

class Window_doppelcharaktere_glade : public Gtk::Window
{   
protected:
        
        
        Window_doppelcharaktere_glade();
        
        ~Window_doppelcharaktere_glade();
};
#endif
