// generated 2001/4/29 19:12:01 CEST by thoma@linux.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.3
//
// Please modify the corresponding derived classes in ./src/Window_angeb_fert.hh and./src/Window_angeb_fert.cc

#ifndef _WINDOW_ANGEB_FERT_GLADE_HH
#  define _WINDOW_ANGEB_FERT_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/clist.h>
#include <gtk--/label.h>

class Window_angeb_fert_glade : public Gtk::Window
{   
protected:
        
        class Gtk::CList *clist_ang_fert_alt;
        class Gtk::CList *clist_ang_fert_neu;
        class Gtk::Label *label_ang_fert;
        
        Window_angeb_fert_glade();
        
        ~Window_angeb_fert_glade();
};
#endif
