// generated 2001/8/13 15:39:24 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/WindowInfo.cc

#include "config.h"
#include "WindowInfo.hh"
#include <gtk--/pixmap.h>
#include "../pixmaps/Phex-mod2-lowcol-20.xpm"
#include <gtk--/table.h>
#include <gtk--/box.h>

WindowInfo_glade::WindowInfo_glade(
) : Gtk::Window(GTK_WINDOW_DIALOG)
{   
   
   Gtk::Window *WindowInfo = this;
   button_info_ok = manage(new class Gtk::Button("OK"));
   
   Gtk::Pixmap *pixmap54 = manage(new class Gtk::Pixmap(Phex_mod2_lowcol_20_xpm));
   infotext = manage(new class Gtk::Label("infotext"));
   
   Gtk::Table *table69 = manage(new class Gtk::Table(2, 2, false));
   Gtk::VBox *vbox4 = manage(new class Gtk::VBox(false, 0));
   button_info_ok->set_usize(50, -1);
   pixmap54->set_alignment(0.5, 0.5);
   pixmap54->set_padding(0, 0);
   infotext->set_usize(350, -1);
   infotext->set_alignment(0.5, 0.5);
   infotext->set_padding(0, 0);
   table69->attach(*button_info_ok, 0, 1, 1, 2, 0, 0, 0, 0);
   table69->attach(*pixmap54, 1, 2, 0, 2, GTK_FILL, GTK_FILL, 0, 0);
   table69->attach(*infotext, 0, 1, 0, 1, GTK_EXPAND|GTK_SHRINK|GTK_FILL, GTK_EXPAND|GTK_SHRINK|GTK_FILL, 0, 0);
   vbox4->pack_start(*table69);
   WindowInfo->set_title("Info");
   WindowInfo->add(*vbox4);
   button_info_ok->show();
   pixmap54->show();
   infotext->show();
   table69->show();
   vbox4->show();
   WindowInfo->show();
   button_info_ok->clicked.connect(SigC::slot(static_cast<class WindowInfo*>(this), &WindowInfo::on_button_info_ok_clicked));
}

WindowInfo_glade::~WindowInfo_glade()
{   
}
