// generated 2002/4/12 10:12:25 CEST by christof@puck.petig-baender.de
// using glademm V0.6.4b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- midgard.glade
// for gtk 2.0.2 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/Window_ruestung.hh and./src/Window_ruestung.cc

#ifndef _WINDOW_RUESTUNG_GLADE_HH
#  define _WINDOW_RUESTUNG_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtk--/window.h>
#include <gtk--/clist.h>
#include <gtk--/label.h>

class Window_ruestung_glade : public Gtk::Window
{  
        
        GlademmData *_data;
protected:
        class Gtk::CList *clist_ruestung;
        class Gtk::Label *label_ruestung;
        
        Window_ruestung_glade();
        
        ~Window_ruestung_glade();
};
#endif
