// generated 2001/8/15 8:35:09 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/Window_Erfahrungspunkte.hh and./src/Window_Erfahrungspunkte.cc

#ifndef _WINDOW_ERFAHRUNGSPUNKTE_GLADE_HH
#  define _WINDOW_ERFAHRUNGSPUNKTE_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/spinbutton.h>

class Window_Erfahrungspunkte_glade : public Gtk::Window
{   
protected:
        
        class Gtk::SpinButton *spinbutton_AEP;
        class Gtk::SpinButton *spinbutton_KEP;
        class Gtk::SpinButton *spinbutton_ZEP;
        
        Window_Erfahrungspunkte_glade();
        
        ~Window_Erfahrungspunkte_glade();
};
#endif
