// generated 2001/4/3 9:39:19 CEST by thoma@ig23.
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/Window_lernpunkte_editieren.hh and./src/Window_lernpunkte_editieren.cc

#ifndef _WINDOW_LERNPUNKTE_EDITIEREN_GLADE_HH
#  define _WINDOW_LERNPUNKTE_EDITIEREN_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/spinbutton.h>
#include <gtk--/button.h>

class Window_lernpunkte_editieren_glade : public Gtk::Window
{   
protected:
        
        class Gtk::SpinButton *lernpunkte_b_ein;
        class Gtk::SpinButton *lernpunkte_f_ein;
        class Gtk::SpinButton *lernpunkte_w_ein;
        class Gtk::SpinButton *lernpunkte_z_ein;
        class Gtk::Button *close;
        
        Window_lernpunkte_editieren_glade();
        
        ~Window_lernpunkte_editieren_glade();
};
#endif
