// generated 2001/5/8 15:14:14 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/Window_hilfe.hh and./src/Window_hilfe.cc

#ifndef _WINDOW_HILFE_GLADE_HH
#  define _WINDOW_HILFE_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/text.h>

class Window_hilfe_glade : public Gtk::Window
{   
protected:
        
        class Gtk::Text *text_hilfe;
        
        Window_hilfe_glade();
        
        ~Window_hilfe_glade();
};
#endif
