// generated 2001/4/30 17:29:59 CEST by thoma@tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/Window_ruestung.hh and./src/Window_ruestung.cc

#ifndef _WINDOW_RUESTUNG_GLADE_HH
#  define _WINDOW_RUESTUNG_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/clist.h>
#include <gtk--/label.h>

class Window_ruestung_glade : public Gtk::Window
{   
protected:
        
        class Gtk::CList *clist_ruestung;
        class Gtk::Label *label_ruestung;
        
        Window_ruestung_glade();
        
        ~Window_ruestung_glade();
};
#endif
