// generated 2001/3/14 22:01:10 CET by thoma@ig23.
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/Window_hilfe.cc

#include "config.h"
#include "Window_hilfe.hh"
#include <gtk--/button.h>
#include <gtk--/scrolledwindow.h>
#include <gtk--/table.h>

Window_hilfe_glade::Window_hilfe_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{   
   
   Gtk::Window *Window_hilfe = this;
   Gtk::Button *button_hilfe_schliessen = manage(new class Gtk::Button("Schließen"));
   text_hilfe = manage(new class Gtk::Text());
   
   Gtk::ScrolledWindow *scrolledwindow25 = manage(new class Gtk::ScrolledWindow());
   Gtk::Table *table35 = manage(new class Gtk::Table(2, 4, false));
   text_hilfe->set_usize(700, 348);
   text_hilfe->set_editable(false);
   text_hilfe->set_word_wrap(false);
   text_hilfe->set_point(0);
   scrolledwindow25->set_policy(GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
   scrolledwindow25->add(*text_hilfe);
   table35->attach(*button_hilfe_schliessen, 3, 4, 1, 2, 0, 0, 5, 5);
   table35->attach(*scrolledwindow25, 0, 4, 0, 1, GTK_EXPAND|GTK_FILL, GTK_EXPAND|GTK_FILL, 0, 0);
   Window_hilfe->set_title("Hilfe");
   Window_hilfe->add(*table35);
   button_hilfe_schliessen->show();
   text_hilfe->show();
   scrolledwindow25->show();
   table35->show();
   Window_hilfe->show();
   button_hilfe_schliessen->clicked.connect(SigC::slot(static_cast<class Window_hilfe*>(this), &Window_hilfe::on_button_hilfe_schliessen_clicked));
}

Window_hilfe_glade::~Window_hilfe_glade()
{   
}
