// $Id: Window_herkunft_glade.cc,v 1.15 2001/04/19 13:29:11 thoma Exp $
/*  Midgard Character Generator
 *  Copyright (C) 2001 Malte Thoma
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

// generated 2001/4/19 8:46:44 CEST by thoma@ig23.
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/Window_herkunft.cc

#include "config.h"
#include "Window_herkunft.hh"
#include <gtk--/pixmap.h>
#include "../pixmaps/CountrChar-trans-50.xpm"
#include <gtk--/label.h>
#include <gtk--/box.h>

Window_herkunft_glade::Window_herkunft_glade(
) : Gtk::Window(GTK_WINDOW_TOPLEVEL)
{   
   
   Gtk::Window *Window_herkunft = this;
   Gtk::Pixmap *pixmap17 = manage(new class Gtk::Pixmap(CountrChar_trans_50_xpm));
   clist_herkunftsland = manage(new class Gtk::CList(2));
   scrolledwindow19 = manage(new class Gtk::ScrolledWindow());
   
   Gtk::VBox *vbox12 = manage(new class Gtk::VBox(false, 0));
   pixmap17->set_alignment(0.5, 0.5);
   pixmap17->set_padding(0, 0);
   clist_herkunftsland->set_usize(274, 360);
   clist_herkunftsland->set_column_title(0, "Kontinent");
   clist_herkunftsland->set_column_width(0, 80);
   clist_herkunftsland->set_column_title(1, "Land");
   clist_herkunftsland->set_column_width(1, 80);
   clist_herkunftsland->column_titles_show();
   scrolledwindow19->set_policy(GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
   scrolledwindow19->add(*clist_herkunftsland);
   vbox12->pack_start(*pixmap17);
   vbox12->pack_start(*scrolledwindow19);
   Window_herkunft->set_title("Herkunft");
   Window_herkunft->add(*vbox12);
   pixmap17->show();
   clist_herkunftsland->show();
   scrolledwindow19->show();
   vbox12->show();
   Window_herkunft->show();
   clist_herkunftsland->select_row.connect(SigC::slot(static_cast<class Window_herkunft*>(this), &Window_herkunft::on_clist_herkunftsland_select_row));
}

Window_herkunft_glade::~Window_herkunft_glade()
{   
}
