// generated 2001/5/25 13:55:39 CEST by christof@puck.(none)
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- midgard.glade
// for gtk 1.2.10 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/Window_herkunft.hh and./src/Window_herkunft.cc

#ifndef _WINDOW_HERKUNFT_GLADE_HH
#  define _WINDOW_HERKUNFT_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/clist.h>
#include <gtk--/scrolledwindow.h>

class Window_herkunft_glade : public Gtk::Window
{   
protected:
        
        class Gtk::CList *clist_herkunftsland;
        class Gtk::ScrolledWindow *scrolledwindow19;
        
        Window_herkunft_glade();
        
        ~Window_herkunft_glade();
};
#endif
