// generated 2001/5/15 23:18:16 CEST by thoma@Tiger.
// using glademm V0.6.2_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/HELP/midgard/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.5
//
// Please modify the corresponding derived classes in ./src/Window_waffe.hh and./src/Window_waffe.cc

#ifndef _WINDOW_WAFFE_GLADE_HH
#  define _WINDOW_WAFFE_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/clist.h>

class Window_waffe_glade : public Gtk::Window
{   
protected:
        
        class Gtk::CList *clist_waffe;
        
        Window_waffe_glade();
        
        ~Window_waffe_glade();
};
#endif
