// generated 2001/4/7 0:48:41 CEST by thoma@ig23.
// using glademm V0.5_11f_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gra_mygen/midgard.glade
// for gtk 1.2.8 and gtkmm 1.2.4
//
// Please modify the corresponding derived classes in ./src/Window_charakter_auswahl.hh and./src/Window_charakter_auswahl.cc

#ifndef _WINDOW_CHARAKTER_AUSWAHL_GLADE_HH
#  define _WINDOW_CHARAKTER_AUSWAHL_GLADE_HH

#include <gtk--/window.h>
#include <gtk--/clist.h>
#include <gtk--/checkbutton.h>

class Window_charakter_auswahl_glade : public Gtk::Window
{   
protected:
        
        class Gtk::CList *clist_charakter_auswahl;
        class Gtk::CheckButton *checkbutton_loeschen;
        
        Window_charakter_auswahl_glade();
        
        ~Window_charakter_auswahl_glade();
};
#endif
