// generated 2002/4/12 10:12:26 CEST by christof@puck.petig-baender.de
// using glademm V0.6.4b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- midgard.glade
// for gtk 2.0.2 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/xml_fileselection.hh and./src/xml_fileselection.cc

#ifndef _XML_FILESELECTION_GLADE_HH
#  define _XML_FILESELECTION_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtk--/accelgroup.h>

class GlademmData
{  
        
        Gtk::AccelGroup *accgrp;
public:
        
        GlademmData(Gtk::AccelGroup *ag) : accgrp(ag)
        {  
        }
        
        Gtk::AccelGroup * getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtk--/fileselection.h>

class xml_fileselection_glade : public Gtk::FileSelection
{  
        
        GlademmData *_data;
protected:
        
        xml_fileselection_glade();
        
        ~xml_fileselection_glade();
};
#endif
