// generated 2003/4/14 22:42:02 CEST by christof@puck.petig-baender.de
// using glademm V1.1.3g_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/christof/berlios/midgard/midgard.glade
// for gtk 2.2.1 and gtkmm 2.2.0
//
// Please modify the corresponding derived classes in ./src/xml_fileselection.hh and./src/xml_fileselection.cc

#ifndef _XML_FILESELECTION_GLADE_HH
#  define _XML_FILESELECTION_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/fileselection.h>

class xml_fileselection_glade : public Gtk::FileSelection
{  
        
        GlademmData *gmm_data;
protected:
        
        xml_fileselection_glade();
        
        ~xml_fileselection_glade();
private:
        virtual void on_cancel_button1_clicked() = 0;
        virtual void on_ok_button1_clicked() = 0;
};
#endif
