// generated 2002/4/12 10:12:26 CEST by christof@puck.petig-baender.de
// using glademm V0.6.4b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- midgard.glade
// for gtk 2.0.2 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/xml_fileselection.cc

#include "config.h"
#include "xml_fileselection.hh"
#include <gdk/gdkkeysyms.h>
#include <gtk--/accelgroup.h>
#include <gtk--/button.h>

xml_fileselection_glade::xml_fileselection_glade(
) : Gtk::FileSelection("XML-Datei auswählen")
{  
   
   Gtk::FileSelection *xml_fileselection = this;
   Gtk::AccelGroup *xml_fileselection_accgrp = Gtk::AccelGroup::create();
   _data = new GlademmData(xml_fileselection_accgrp);
   xml_fileselection->get_ok_button()->set_flags(GTK_CAN_FOCUS);
   xml_fileselection->get_cancel_button()->set_flags(GTK_CAN_FOCUS);
   xml_fileselection->set_border_width(10);
   xml_fileselection->set_title("XML-Datei auswählen");
   xml_fileselection->set_modal(true);
   xml_fileselection->add_accel_group(*(_data->getAccelGroup()));
   xml_fileselection->show();
   xml_fileselection->get_ok_button()->clicked.connect(SigC::slot(static_cast<class xml_fileselection*>(this), &xml_fileselection::on_ok_button1_clicked));
   xml_fileselection->get_cancel_button()->clicked.connect(SigC::slot(static_cast<class xml_fileselection*>(this), &xml_fileselection::on_cancel_button1_clicked));
}

xml_fileselection_glade::~xml_fileselection_glade()
{  delete _data;
}
