// generated 2002/3/26 22:01:42 CET by thoma@Tiger.(none)
// using glademm V0.6.4b_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/midgard/programme/gcc_3.0/midgard/midgard.glade
// for gtk 1.2.10 and gtkmm 1.2.8
//
// Please modify the corresponding derived classes in ./src/xml_fileselection.hh and./src/xml_fileselection.cc

#ifndef _XML_FILESELECTION_GLADE_HH
#  define _XML_FILESELECTION_GLADE_HH

#include <gtk--/fileselection.h>

class xml_fileselection_glade : public Gtk::FileSelection
{  
protected:
        
        
        xml_fileselection_glade();
        
        ~xml_fileselection_glade();
};
#endif
